/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;


import controller.Controladora;
import controller.Validacion;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author GREGORIO-PC
 */
public class AgregarPersonal extends javax.swing.JFrame {

    Controladora control = new Controladora();
    Validacion valida = new Validacion();
    private JFrame ventana; 
    
    public AgregarPersonal() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setResizable(false); 
        valida.tomarFoco(txtCedula);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAtras = new javax.swing.JButton();
        botonAgregar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        botonHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSegundoApellido = new javax.swing.JTextField();
        txtPrimerApellido = new javax.swing.JTextField();
        txtPrimerNombre = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtSegundoNombre = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        txtTelefono1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCorreo1 = new javax.swing.JTextField();
        txtTelefono2 = new javax.swing.JTextField();
        txtTitulacion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtOtroDato = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtBeneficiario1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtbeneficiario1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCorreo2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        txtMunicipio = new javax.swing.JTextField();
        txtOtro = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtReb1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        comboDia = new javax.swing.JComboBox<>();
        comboMes = new javax.swing.JComboBox<>();
        comboAño = new javax.swing.JComboBox<>();
        txtBeneficiario3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonAtras.setText("Atrás");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(botonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 509, -1, -1));

        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(botonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 503, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonHome.setText("HOME");
        botonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHomeActionPerformed(evt);
            }
        });
        jPanel1.add(botonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 37));

        jLabel1.setText("CI :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 62, -1, -1));

        jLabel2.setText("Primer nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 62, -1, -1));

        jLabel3.setText("Segundo Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 106, -1, -1));

        jLabel4.setText("Primer apellido: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 115, -1, -1));

        jLabel5.setText("Segundo apellido:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 152, -1, -1));

        jLabel6.setText("Titulación: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 232, -1, -1));
        jPanel1.add(txtSegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 149, 113, -1));

        txtPrimerApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimerApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(txtPrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 112, 104, -1));
        jPanel1.add(txtPrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 59, 99, -1));

        txtCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCedulaMousePressed(evt);
            }
        });
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 59, 112, -1));
        jPanel1.add(txtSegundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 103, 112, -1));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 59, 99, -1));
        jPanel1.add(txtTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 150, 100, -1));

        jLabel9.setText("telefono 1:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 150, -1, -1));

        jLabel10.setText("telefono 2:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 197, -1, -1));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 175, -1, 77));

        jLabel12.setText("Correo 2:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 235, 63, -1));

        jLabel13.setText("Correo 1:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 197, -1, -1));
        jPanel1.add(txtCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 188, 100, -1));
        jPanel1.add(txtTelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 194, 113, -1));
        jPanel1.add(txtTitulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 232, 100, -1));

        jLabel14.setText("Fecha  Contrato:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 394, -1, -1));

        jLabel15.setText("Otro dato:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));
        jPanel1.add(txtOtroDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 270, 113, -1));

        jLabel16.setText("Beneficiario 1:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 273, -1, -1));
        jPanel1.add(txtBeneficiario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 59, 100, -1));

        jLabel17.setText("Beneficiario 2:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 316, 70, -1));
        jPanel1.add(txtbeneficiario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 270, 100, -1));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 357, 68, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Agregar Personal");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 0, -1, -1));
        jPanel1.add(txtCorreo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 232, 113, -1));

        jLabel8.setText("Direccion : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 432, -1, -1));
        jPanel1.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 429, 90, -1));
        jPanel1.add(txtMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 429, 110, -1));
        jPanel1.add(txtOtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 429, 113, -1));

        jLabel23.setText(" Dia");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 394, -1, -1));

        jLabel24.setText("Mes");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 394, -1, -1));

        jLabel25.setText("Año");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 394, -1, -1));

        jLabel20.setText("Estado");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 460, -1, -1));

        jLabel21.setText("Municipio");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 460, -1, -1));

        jLabel22.setText("Av / calle");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, -1, -1));

        jLabel26.setText("Red social 1:");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));
        jPanel1.add(txtReb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 310, 100, -1));

        jLabel27.setText("Red social 2:");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 354, -1, 20));

        comboDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(comboDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 391, -1, -1));

        comboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));
        jPanel1.add(comboMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 391, -1, -1));

        comboAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));
        jPanel1.add(comboAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 391, -1, -1));
        jPanel1.add(txtBeneficiario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 313, 113, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 350, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 610, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrimerApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimerApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimerApellidoActionPerformed

    private void botonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHomeActionPerformed
        Home ventana = new Home();
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_botonHomeActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
         MenuPersonal ventana = new MenuPersonal();
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
    String fecha =" ";
    fecha = comboDia.getSelectedItem()+"-"+comboMes.getSelectedItem()+"-"+comboAño.getSelectedItem();
    if (Integer.parseInt(txtCedula.getText()) !=0 ){
    if (control.buscarPersonal(Integer.parseInt(txtCedula.getText()))!= 1 ){
    
    int verificarAgregar;
      verificarAgregar= control.agregarPersonal(Integer.parseInt(txtCedula.getText()), txtPrimerNombre.getText(),txtSegundoNombre.getText(),txtPrimerApellido.getText(),txtSegundoApellido.getText(),fecha,txtOtroDato.getText());
      if (verificarAgregar == 1){
          JOptionPane.showMessageDialog(null, "Personal " + txtPrimerNombre.getText(), " agregado con exito!", JOptionPane.INFORMATION_MESSAGE);
           MenuPersonal ventana = new MenuPersonal();
           ventana.setLocationRelativeTo(null);
           ventana.setVisible(true);
           this.dispose(); 
      }
           
      else
          if (verificarAgregar == 0)
          JOptionPane.showMessageDialog(null, "Personal " + txtPrimerNombre.getText(), " No se pudo agregar!", JOptionPane.ERROR_MESSAGE);
    }
    else
         JOptionPane.showMessageDialog(null, "Personal " + txtPrimerNombre.getText(), " Cedula ya registrada!", JOptionPane.ERROR_MESSAGE);
    }
    else
         JOptionPane.showMessageDialog(null, "ERROR " , " La cedula no puede ser cero!", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
      
           
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtCedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedulaMousePressed
        
    }//GEN-LAST:event_txtCedulaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonHome;
    private javax.swing.JComboBox<String> comboAño;
    private javax.swing.JComboBox<String> comboDia;
    private javax.swing.JComboBox<String> comboMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField txtBeneficiario1;
    private javax.swing.JTextField txtBeneficiario3;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo1;
    private javax.swing.JTextField txtCorreo2;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtOtro;
    private javax.swing.JTextField txtOtroDato;
    private javax.swing.JTextField txtPrimerApellido;
    private javax.swing.JTextField txtPrimerNombre;
    private javax.swing.JTextField txtReb1;
    private javax.swing.JTextField txtSegundoApellido;
    private javax.swing.JTextField txtSegundoNombre;
    private javax.swing.JTextField txtTelefono1;
    private javax.swing.JTextField txtTelefono2;
    private javax.swing.JTextField txtTitulacion;
    private javax.swing.JTextField txtbeneficiario1;
    // End of variables declaration//GEN-END:variables
}
