/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import controller.Controladora;
import controller.Validacion;


import interfaz.PedirRif;
import java.awt.event.ItemEvent;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat; //MANEJO DE FECHAS
import javax.swing.JComboBox;
/**
 *
 * @author Michele
 */
public class ConModProveedor extends javax.swing.JFrame {

private JFrame ventana;   
 Controladora control = new Controladora();
 String nombreUsuario="";
 String nombreEntidad="proveedor";
String instruccion="modificar";
//    Validacion valida = new Validacion();
    String nombreActual;
    /**
     * Creates new form ConModProveedor
     */
    public ConModProveedor(String nombre,String nombreUsuario) {
        initComponents();
         this.setLocationRelativeTo(null);
        this.setResizable(false); 
    nombreActual=nombre;
    this.nombreUsuario=nombreUsuario;
   control.llenar_pais(PaisCombo);

    NombreTxt.setEnabled(false);
 PaisCombo.setVisible(false);
EstadoCombo.setVisible(false);
MunicipioCombo.setVisible(false);
 ParroquiaCombo.setVisible(false);
 

   PaisTxt.setEnabled(false);
     EstadoTxt.setEnabled(false);
     MunicipioTxt.setEnabled(false);
  ParroquiaTxt.setEnabled(false);
  
    control.llenarVentaProveedor(nombre,NombreTxt,pagWebTxt,Tlf1Txt,montoAcreditadoTxt,calendar,CorreoTxt,ParroquiaTxt,MunicipioTxt,EstadoTxt,PaisTxt);
  montoAcreditadoTxt.setEnabled(false);
    Tlf1Txt.setEnabled(false);
    pagWebTxt.setEnabled(false);
    calendar.setEnabled(false);
    Guardar.setVisible(false);
    CorreoTxt.setEnabled(false);

    }

    private ConModProveedor() {

     initComponents();
         this.setLocationRelativeTo(null);
        this.setResizable(false); 
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        Modificar = new javax.swing.JButton();
        Atras = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        NombreTxt = new javax.swing.JTextField();
        pagWebTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        calendar = new com.toedter.calendar.JDateChooser();
        montoAcreditadoTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Tlf1Txt = new javax.swing.JTextField();
        CorreoTxt = new javax.swing.JTextField();
        Correo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PaisCombo = new javax.swing.JComboBox();
        EstadoCombo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        MunicipioCombo = new javax.swing.JComboBox();
        ParroquiaCombo = new javax.swing.JComboBox();
        Parroquia = new javax.swing.JLabel();
        PaisTxt = new javax.swing.JTextField();
        EstadoTxt = new javax.swing.JTextField();
        MunicipioTxt = new javax.swing.JTextField();
        ParroquiaTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Proveedor");

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Atras.setText("Atrás");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        jButton1.setText("home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        NombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTxtActionPerformed(evt);
            }
        });

        pagWebTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagWebTxtActionPerformed(evt);
            }
        });

        jLabel2.setText("Página web:");

        jLabel1.setText("Nombre:");

        jLabel14.setText("Fecha  Contrato:");

        jLabel10.setText("Monto Acreditado:");

        jLabel3.setText("Teléfono:");

        Tlf1Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tlf1TxtActionPerformed(evt);
            }
        });

        Correo.setText("Correo:");

        jLabel7.setText("País:");

        PaisCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione País" }));
        PaisCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                PaisComboItemStateChanged(evt);
            }
        });
        PaisCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaisComboActionPerformed(evt);
            }
        });

        EstadoCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Estado" }));
        EstadoCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                EstadoComboItemStateChanged(evt);
            }
        });
        EstadoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadoComboActionPerformed(evt);
            }
        });

        jLabel8.setText("Estado:");

        jLabel9.setText("Municipio:");

        MunicipioCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Municipio", " " }));
        MunicipioCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MunicipioComboItemStateChanged(evt);
            }
        });
        MunicipioCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MunicipioComboActionPerformed(evt);
            }
        });

        ParroquiaCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Parroquia", " " }));

        Parroquia.setText("Parroquia:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(Atras))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Guardar)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Parroquia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ParroquiaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(PaisCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EstadoCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(MunicipioCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PaisTxt)
                            .addComponent(EstadoTxt)
                            .addComponent(MunicipioTxt)
                            .addComponent(ParroquiaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Tlf1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(montoAcreditadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(43, 43, 43)
                                    .addComponent(Correo)
                                    .addGap(18, 18, 18)
                                    .addComponent(CorreoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pagWebTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(pagWebTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(PaisCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PaisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(EstadoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EstadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(MunicipioCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(MunicipioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Parroquia)
                            .addComponent(ParroquiaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ParroquiaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(montoAcreditadoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tlf1Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Correo)
                            .addComponent(CorreoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(315, 315, 315)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Atras)
                    .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Guardar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
     
        NombreTxt.setEnabled(true);
  PaisTxt.setVisible(false);
     EstadoTxt.setVisible(true);
     MunicipioTxt.setVisible(true);
  ParroquiaTxt.setVisible(true);
               PaisCombo.setVisible(true);
EstadoCombo.setVisible(true);
MunicipioCombo.setVisible(true);
 ParroquiaCombo.setVisible(true);
        Tlf1Txt.setEnabled(true);
        montoAcreditadoTxt.setEnabled(true);
        pagWebTxt.setEnabled(true);
       calendar.setEnabled(true);
         CorreoTxt.setEnabled(true);
        Guardar.setVisible(true);
        Modificar.setVisible(false);
    }//GEN-LAST:event_ModificarActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        PedirRif ventana = new PedirRif(nombreUsuario);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_AtrasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Home ventana = new Home(nombreUsuario);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        try{
              int permiso=0;
      if (control.buscarPermiso(instruccion, nombreEntidad,nombreUsuario)==1){
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
String fecha = sdf.format(calendar.getDate());

int lugar = control.BuscarLugarID(ParroquiaCombo.getSelectedItem().toString(),"Parroquia");
        
        if ((NombreTxt.getText().isEmpty()== false ) || (Tlf1Txt.getText().isEmpty()== false ) || (CorreoTxt.getText().isEmpty()== false )){     
              if ((control.buscarProveedor((NombreTxt.getText()))!= 1 ) ||(control.buscarTelefono((Tlf1Txt.getText()))!= 1 )){
     
             int verificar = control.modificarProveedor(nombreActual,NombreTxt.getText(),pagWebTxt.getText(),fecha,Integer.parseInt(montoAcreditadoTxt.getText()),Tlf1Txt.getText(),CorreoTxt.getText(),lugar);
    
            if (verificar == 1){
             JOptionPane.showMessageDialog(null, "Proveedor " + NombreTxt.getText(), " Modificado con exito!", JOptionPane.INFORMATION_MESSAGE);
              Menu_Proveedores ventana = new Menu_Proveedores(nombreUsuario);
              ventana.setLocationRelativeTo(null);
              ventana.setVisible(true);
              this.dispose();
            }
            else{
               
               JOptionPane.showMessageDialog(null, "Proveedor " + NombreTxt.getText(), "No se pudo Modificar!", JOptionPane.ERROR_MESSAGE);
                Menu_Proveedores ventana = new Menu_Proveedores(nombreUsuario);
                ventana.setLocationRelativeTo(null);
                ventana.setVisible(true);
                this.dispose();
             }
        }
     
      else{
             if ((control.devolverNombre(NombreTxt.getText()).equals(nombreActual)) ){
                     
                 int verificar = control.modificarProveedor(nombreActual,NombreTxt.getText(),pagWebTxt.getText(),fecha,Integer.parseInt(montoAcreditadoTxt.getText()),Tlf1Txt.getText(),CorreoTxt.getText(),lugar);
                   if (verificar == 1){
                   JOptionPane.showMessageDialog(null, "Proveedor " + NombreTxt.getText(), " Modificado con exito!", JOptionPane.INFORMATION_MESSAGE);
                    Menu_Proveedores ventana = new Menu_Proveedores(nombreUsuario);
                  ventana.setLocationRelativeTo(null);
                  ventana.setVisible(true);
                 this.dispose();
                 }
             else{
               JOptionPane.showMessageDialog(null, "Proveedor " + NombreTxt.getText(), "No se pudo Modificar!", JOptionPane.ERROR_MESSAGE);
               Menu_Proveedores ventana = new Menu_Proveedores(nombreUsuario);
                ventana.setLocationRelativeTo(null);
                ventana.setVisible(true);
                this.dispose();
             }
                  
             }
             else

                 JOptionPane.showMessageDialog(null, "Proveedor " + NombreTxt.getText(), "Nombre ya registrado", JOptionPane.ERROR_MESSAGE);
       }
     }
     else
      JOptionPane.showMessageDialog(null, "Error  ", "El Nombre no puede estar vacio", JOptionPane.ERROR_MESSAGE);
      }
      else
           JOptionPane.showMessageDialog(null, "Acceso No Permitido "  , "Su Usuario no tiene este Privilegio ", JOptionPane.ERROR_MESSAGE); 
            

        }catch(Exception e){
             JOptionPane.showMessageDialog(null, "Ocurrio un error!", " Error", JOptionPane.ERROR_MESSAGE);
   }
    }//GEN-LAST:event_GuardarActionPerformed

    private void NombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtActionPerformed

    private void pagWebTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagWebTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagWebTxtActionPerformed

    private void Tlf1TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tlf1TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tlf1TxtActionPerformed

    private void PaisComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_PaisComboItemStateChanged
        int     pais = 0;
        if (evt.getStateChange()== ItemEvent.SELECTED)
        pais = control.BuscarLugarID(PaisCombo.getSelectedItem().toString(),"Pais");
        control.llenar_est(EstadoCombo,pais);
    }//GEN-LAST:event_PaisComboItemStateChanged

    private void PaisComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaisComboActionPerformed

    }//GEN-LAST:event_PaisComboActionPerformed

    private void EstadoComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_EstadoComboItemStateChanged
        int     estado = 0;
        if (evt.getStateChange()== ItemEvent.SELECTED)
        estado = control.BuscarLugarID(EstadoCombo.getSelectedItem().toString(),"Estado");
      
        control.llenar_muni(MunicipioCombo,estado);
    }//GEN-LAST:event_EstadoComboItemStateChanged

    private void EstadoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadoComboActionPerformed

    }//GEN-LAST:event_EstadoComboActionPerformed

    private void MunicipioComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MunicipioComboItemStateChanged
        int     muni = 0;
        if (evt.getStateChange()== ItemEvent.SELECTED)
        muni = control.BuscarLugarID(MunicipioCombo.getSelectedItem().toString(),"Municipio");

        control.llenar_parro(ParroquiaCombo,muni);
    }//GEN-LAST:event_MunicipioComboItemStateChanged

    private void MunicipioComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MunicipioComboActionPerformed

    }//GEN-LAST:event_MunicipioComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConModProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConModProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConModProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConModProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConModProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JLabel Correo;
    private javax.swing.JTextField CorreoTxt;
    private javax.swing.JComboBox EstadoCombo;
    private javax.swing.JTextField EstadoTxt;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Modificar;
    private javax.swing.JComboBox MunicipioCombo;
    private javax.swing.JTextField MunicipioTxt;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JComboBox PaisCombo;
    private javax.swing.JTextField PaisTxt;
    private javax.swing.JLabel Parroquia;
    private javax.swing.JComboBox ParroquiaCombo;
    private javax.swing.JTextField ParroquiaTxt;
    private javax.swing.JTextField Tlf1Txt;
    private com.toedter.calendar.JDateChooser calendar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField montoAcreditadoTxt;
    private javax.swing.JTextField pagWebTxt;
    // End of variables declaration//GEN-END:variables
}
