/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import controller.Controladora;
import controller.Validacion;


import java.awt.event.ItemEvent;
import java.text.SimpleDateFormat; 
import javax.swing.JOptionPane;

/**
 *
 * @author Fabian Graterol
 */
public class Consultar_cliente extends javax.swing.JFrame {

 Controladora control = new Controladora();
 String nombreEntidad="cliente";
 String instruccion="modificar";
 String nombreUsuario="";
// Validacion valida = new Validacion();
 String nombre;
    /**
     * Creates new form Consultar_cliente
     */
    public Consultar_cliente(String nombrec,String nombreUsuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false); 
        nombre=nombrec;
        this.nombreUsuario=nombreUsuario;
        Nombre_text.setEnabled(false);
        pagina_text.setEnabled(false);
        fecha.setEnabled(false);
        monto_text.setEnabled(false);
        telf_text.setEnabled(false);
        correo_text.setEnabled(false);
        otro_text.setEnabled(false);
        Pais_combo.setVisible(false);
        estado_combo.setVisible(false);
        municipio_combo.setVisible(false);
        parroquia_combo.setVisible(false);
        pais_text.setEnabled(false);
        estado_text.setEnabled(false);
        municipio_text.setEnabled(false);
        parroquia_text.setEnabled(false);
        guardar.setVisible(false);
        
        control.llenar_pais(Pais_combo);
        control.llenarCliente(nombre,Nombre_text,pagina_text,fecha,monto_text,telf_text,correo_text,otro_text,pais_text,estado_text,municipio_text,parroquia_text);
    }
    public Consultar_cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Atras = new javax.swing.JButton();
        pais_text = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        estado_text = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        Nombre_text = new javax.swing.JTextField();
        municipio_text = new javax.swing.JTextField();
        parroquia_text = new javax.swing.JTextField();
        pagina_text = new javax.swing.JTextField();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        monto_text = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        telf_text = new javax.swing.JTextField();
        correo_text = new javax.swing.JTextField();
        Correo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Pais_combo = new javax.swing.JComboBox();
        estado_combo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        municipio_combo = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        parroquia_combo = new javax.swing.JComboBox();
        modificar = new javax.swing.JButton();
        Parroquia = new javax.swing.JLabel();
        otro_text = new javax.swing.JTextField();
        Otro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Atras.setText("Atras");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        Nombre_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_textActionPerformed(evt);
            }
        });

        pagina_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagina_textActionPerformed(evt);
            }
        });

        jLabel2.setText("Página web:");

        jLabel1.setText("Nombre:");

        jLabel14.setText("Fecha  Contrato:");

        jLabel10.setText("Monto Acreditado:");

        jLabel3.setText("Teléfono:");

        telf_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telf_textActionPerformed(evt);
            }
        });

        Correo.setText("Correo:");

        jLabel7.setText("País:");

        Pais_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione País" }));
        Pais_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Pais_comboItemStateChanged(evt);
            }
        });
        Pais_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pais_comboActionPerformed(evt);
            }
        });

        estado_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Estado" }));
        estado_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estado_comboItemStateChanged(evt);
            }
        });
        estado_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estado_comboActionPerformed(evt);
            }
        });

        jLabel8.setText("Estado:");

        jLabel9.setText("Municipio:");

        municipio_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Municipio", " " }));
        municipio_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                municipio_comboItemStateChanged(evt);
            }
        });
        municipio_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipio_comboActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Cliente - Modificar");

        parroquia_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Parroquia", "" }));

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        Parroquia.setText("Parroquia:");

        Otro.setText("Otro dato:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Parroquia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(parroquia_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Pais_combo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(estado_combo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(municipio_combo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pais_text, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                    .addComponent(estado_text)
                                    .addComponent(municipio_text)
                                    .addComponent(parroquia_text)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                                .addComponent(monto_text)
                                                .addComponent(telf_text)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(51, 51, 51)
                                            .addComponent(Correo)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(correo_text, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pagina_text, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                            .addComponent(Nombre_text))
                                        .addGap(1, 1, 1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Otro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(otro_text, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(51, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(Atras))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(modificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(guardar)
                                .addGap(43, 43, 43))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jLabel11)
                                .addContainerGap(156, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Nombre_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(pagina_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Pais_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pais_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(estado_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(estado_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(municipio_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(municipio_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Parroquia)
                            .addComponent(parroquia_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parroquia_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(monto_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telf_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Correo)
                            .addComponent(correo_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Otro)
                    .addComponent(otro_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Atras)
                    .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        Pedir_Rif_cliente ventana = new Pedir_Rif_cliente(nombreUsuario);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AtrasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Home ventana = new Home(nombreUsuario);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
//     Validacion valida = new Validacion();
    int permiso=0;
      if (control.buscarPermiso(instruccion, nombreEntidad,nombreUsuario)==1){ 
        if(!(parroquia_combo.getSelectedItem().toString().equalsIgnoreCase("Seleccione Parroquia"))){
        int check1=0;
       int check2=0;
       String telfActual=telf_text.getText();
        if ((Nombre_text.getText().isEmpty() ==false )&& (pagina_text.getText().isEmpty()==false) && (monto_text.getText().isEmpty()==false) && (telf_text.getText().isEmpty()==false) && (correo_text.getText().isEmpty()==false)){
            if (!(nombre.equals(Nombre_text.getText())))
                check1=control.buscarCliente(Nombre_text.getText());
            if (!(telfActual.equals(telf_text.getText())))
                check2=control.buscarTelefono(telf_text.getText());
            if (check1!=1 && check2!=1){
                SimpleDateFormat date= new SimpleDateFormat("yyyy-MM-dd");
                String fechac= date.format(fecha.getDate());
                int lugar =control.BuscarLugarID(parroquia_combo.getSelectedItem().toString(), "Parroquia");
                control.modificarCliente(nombre,Nombre_text.getText(), pagina_text.getText(),otro_text.getText(),fechac, Integer.parseInt(monto_text.getText()), lugar, telf_text.getText(),correo_text.getText());
                nombre=Nombre_text.getText();
                telfActual=telf_text.getText();
                JOptionPane.showMessageDialog(null, "Con Exito  ", "Modificado", JOptionPane.INFORMATION_MESSAGE);
                
            }
            else if (check1==1 && check2==1)
                JOptionPane.showMessageDialog(null, "Error  ", "Cliente y telefono ya registrados!", JOptionPane.ERROR_MESSAGE);
            else if (check2==1)
                    JOptionPane.showMessageDialog(null, "Error  ", "El telefono "+telf_text.getText()+" ya esta registrado!", JOptionPane.ERROR_MESSAGE);
            
            else if (check1==1)
                JOptionPane.showMessageDialog(null, "Error  ", "El cliente "+Nombre_text.getText()+" ya esta registrado!", JOptionPane.ERROR_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(null, "Falta llenar campos obligatorios", " Error", JOptionPane.ERROR_MESSAGE);
     }else{
         JOptionPane.showMessageDialog(null, "Ocurrio un error!", " Error", JOptionPane.ERROR_MESSAGE);
         
     }
      }
      else
           JOptionPane.showMessageDialog(null, "Acceso No Permitido "  , "Su Usuario no tiene este Privilegio ", JOptionPane.ERROR_MESSAGE); 
                
         
        
        /* SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");

        String fecha = sdf.format(calendar.getDate());
        int lugar = control.BuscarLugarID(ParroquiaCombo.getSelectedItem().toString(),"Parroquia");

        if ((NombreTxt.getText().isEmpty()== false ) || (Tlf1Txt.getText().isEmpty()== false ) || (CorreoTxt.getText().isEmpty()== false )){
            if ((control.buscarProveedor((NombreTxt.getText()))!= 1 )&& (control.buscarTelefono((Tlf1Txt.getText()))!= 1 )){

                int verificar = control.modificarProveedor(nombreActual,NombreTxt.getText(),pagWebTxt.getText(),fecha,Integer.parseInt(montoAcreditadoTxt.getText()),Tlf1Txt.getText(),CorreoTxt.getText(),lugar);

                if (verificar == 1){
                    JOptionPane.showMessageDialog(null, "Proveedor " + NombreTxt.getText(), " Modificado con exito!", JOptionPane.INFORMATION_MESSAGE);
                    MenuProveedor ventana = new MenuProveedor();
                    ventana.setLocationRelativeTo(null);
                    ventana.setVisible(true);
                    this.dispose();
                }
                else{

                    JOptionPane.showMessageDialog(null, "Proveedor " + NombreTxt.getText(), "No se pudo Modificar!", JOptionPane.ERROR_MESSAGE);
                    MenuProveedor ventana = new MenuProveedor();
                    ventana.setLocationRelativeTo(null);
                    ventana.setVisible(true);
                    this.dispose();
                }
            }

            else{
                if ((control.devolverNombre(NombreTxt.getText()).equals(nombreActual)) || (control.devolverTelefono(NombreTxt.getText()) == Integer.parseInt(Tlf1Txt.getText()))){

                    int verificar = control.modificarProveedor(nombreActual,NombreTxt.getText(),pagWebTxt.getText(),fecha,Integer.parseInt(montoAcreditadoTxt.getText()),Tlf1Txt.getText(),CorreoTxt.getText(),lugar);
                    if (verificar == 1){
                        JOptionPane.showMessageDialog(null, "Proveedor " + NombreTxt.getText(), " Modificado con exito!", JOptionPane.INFORMATION_MESSAGE);
                        MenuProveedor ventana = new MenuProveedor();
                        ventana.setLocationRelativeTo(null);
                        ventana.setVisible(true);
                        this.dispose();
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Proveedor " + NombreTxt.getText(), "No se pudo Modificar!", JOptionPane.ERROR_MESSAGE);
                        MenuProveedor ventana = new MenuProveedor();
                        ventana.setLocationRelativeTo(null);
                        ventana.setVisible(true);
                        this.dispose();
                    }

                }
                else

                JOptionPane.showMessageDialog(null, "Proveedor " + NombreTxt.getText(), "Nombre ya registrado", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        JOptionPane.showMessageDialog(null, "Error  ", "El Nombre no puede estar vacio", JOptionPane.ERROR_MESSAGE);
*/
    }//GEN-LAST:event_guardarActionPerformed

    private void Nombre_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_textActionPerformed

    private void pagina_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagina_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagina_textActionPerformed

    private void telf_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telf_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telf_textActionPerformed

    private void Pais_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Pais_comboItemStateChanged
        int     pais = 0;
        if (evt.getStateChange()== ItemEvent.SELECTED)
        pais = control.BuscarLugarID(Pais_combo.getSelectedItem().toString(),"Pais");
        control.llenar_est(estado_combo,pais);
    }//GEN-LAST:event_Pais_comboItemStateChanged

    private void Pais_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pais_comboActionPerformed

    }//GEN-LAST:event_Pais_comboActionPerformed

    private void estado_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_estado_comboItemStateChanged
        int     estado = 0;
        if (evt.getStateChange()== ItemEvent.SELECTED)
        estado = control.BuscarLugarID(estado_combo.getSelectedItem().toString(),"Estado");

        control.llenar_muni(municipio_combo,estado);
    }//GEN-LAST:event_estado_comboItemStateChanged

    private void estado_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estado_comboActionPerformed

    }//GEN-LAST:event_estado_comboActionPerformed

    private void municipio_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_municipio_comboItemStateChanged
        int     muni = 0;
        if (evt.getStateChange()== ItemEvent.SELECTED)
        muni = control.BuscarLugarID(municipio_combo.getSelectedItem().toString(),"Municipio");

        control.llenar_parro(parroquia_combo,muni);
    }//GEN-LAST:event_municipio_comboItemStateChanged

    private void municipio_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municipio_comboActionPerformed

    }//GEN-LAST:event_municipio_comboActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed

        Nombre_text.setEnabled(true);
        pagina_text.setEnabled(true);
        fecha.setEnabled(true);
        monto_text.setEnabled(true);
        telf_text.setEnabled(true);
        correo_text.setEnabled(true);
        otro_text.setEnabled(true);
              
        guardar.setVisible(true);
        modificar.setVisible(false); 
        Pais_combo.setVisible(true);
        estado_combo.setVisible(true);
        municipio_combo.setVisible(true);
        parroquia_combo.setVisible(true);
       
        pais_text.setEnabled(false);
        estado_text.setEnabled(false);
        municipio_text.setEnabled(false);
        parroquia_text.setEnabled(false);
    }//GEN-LAST:event_modificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JLabel Correo;
    private javax.swing.JTextField Nombre_text;
    private javax.swing.JLabel Otro;
    private javax.swing.JComboBox Pais_combo;
    private javax.swing.JLabel Parroquia;
    private javax.swing.JTextField correo_text;
    private javax.swing.JComboBox estado_combo;
    private javax.swing.JTextField estado_text;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JButton guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField monto_text;
    private javax.swing.JComboBox municipio_combo;
    private javax.swing.JTextField municipio_text;
    private javax.swing.JTextField otro_text;
    private javax.swing.JTextField pagina_text;
    private javax.swing.JTextField pais_text;
    private javax.swing.JComboBox parroquia_combo;
    private javax.swing.JTextField parroquia_text;
    private javax.swing.JTextField telf_text;
    // End of variables declaration//GEN-END:variables
}
