/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import controller.Controladora;
import java.text.DateFormat;
import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/**
 *
 * @author GREGORIO-PC
 */
public class DetallesProcesoPieza1 extends javax.swing.JFrame {
Controladora control = new Controladora();
int idAvionVentana;
int idProcesoActual;
String nombreUsuario="";
    /**
     * Creates new form DetallesProcesoPieza
     */
    public DetallesProcesoPieza1() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        
    }
        public DetallesProcesoPieza1(int idProceso_1,int idAvion,String nombreProceso,String nombreUsuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.nombreUsuario=nombreUsuario;
        idAvionVentana=idAvion;
        String idAvionParaAsignarLbl;
        idAvionParaAsignarLbl=String.valueOf(idAvion);
        lblIdAvion.setText(idAvionParaAsignarLbl);
        idProcesoActual=idProceso_1;
        this.nombreProceso.setText(nombreProceso);
//        control.llenarComboEstaus(comboEstatus);
        if (nombreProceso.equals("Ensamblaje")){
           control.llenarVentaDetallesEnsamblaPieza(idProceso_1,idProceso, nombrePlanta, lblFecha_i,  lblFecha_f, lblEstatus,nombreEncargado,cedula,telefono,lblPieza,lblTipoPieza);
           txtFecha_f.setText(lblFecha_f.getText());
           control.llenarComboEstatusPiezaDetalle(comboEstatus);
//           comboEstatus.setSelectedItem(lblEstatus.getText());
         
           control.llenarTablaPersonalEnsamblajePieza(tablaPersonal,idProceso_1);
           
           if(lblEstatus.getText().equals("finalizado")){
              comboEstatus.setEnabled(false);
              guardar.setEnabled(false);
              txtFecha_f.setEnabled(false);
            }
        }
        else
            if   (nombreProceso.equals("Prueba")){
                control.llenarVentaDetallesPruebaPieza(idProceso_1, idProceso, nombrePlanta, lblFecha_i, lblFecha_f, lblEstatus, nombreEncargado,cedula, telefono,lblPieza,lblTipoPieza);
                control.llenarTablaPersonalPruebaPieza(tablaPersonal, idProceso_1);
                txtFecha_f.setText(lblFecha_f.getText());
//               comboEstatus.setSelectedItem(lblEstatus.getText());
               control.llenarComboEstatusPruebaDetalle(comboEstatus);
                if(lblEstatus.getText().equals("satisfactorio") || lblEstatus.getText().equals("insatisfactorio")){
                   comboEstatus.setEnabled(false);
                   guardar.setEnabled(false);
                   txtFecha_f.setEnabled(false);
                }
            }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPersonal = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        idProceso = new javax.swing.JLabel();
        nombreProceso = new javax.swing.JLabel();
        lblFecha_i = new javax.swing.JLabel();
        nombrePlanta = new javax.swing.JLabel();
        nombreEncargado = new javax.swing.JLabel();
        cedula = new javax.swing.JLabel();
        telefono = new javax.swing.JLabel();
        Home = new javax.swing.JButton();
        txtFecha_f = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        Atras = new javax.swing.JButton();
        lblFecha_f = new javax.swing.JLabel();
        lblEstatus = new javax.swing.JLabel();
        comboEstatus = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblPieza = new javax.swing.JLabel();
        lblTipoPieza = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblIdAvion = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Detalles del Proceso");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 18, -1, -1));

        jLabel2.setText("Id del Proceso:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel3.setText("Proceso :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel4.setText("Fecha de inicico:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel5.setText("Fecha final:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jLabel6.setText("Estatus:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel7.setText("Planta:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel8.setText("Encargado:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        jLabel9.setText("Cedula:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        jLabel10.setText("Telefono:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        tablaPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cedula", "Nombre y Apellido", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaPersonal);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 479, 229));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Personal");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        idProceso.setText("id");
        jPanel1.add(idProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        nombreProceso.setText("nombre");
        jPanel1.add(nombreProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        lblFecha_i.setText("00-00-000");
        jPanel1.add(lblFecha_i, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, 20));

        nombrePlanta.setText("nombre");
        jPanel1.add(nombrePlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        nombreEncargado.setText("nombre");
        jPanel1.add(nombreEncargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        cedula.setText("cedula");
        jPanel1.add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        telefono.setText("0414");
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        jPanel1.add(txtFecha_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 160, -1));

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        Atras.setText("Atras");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        jPanel1.add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, -1, -1));

        lblFecha_f.setText("fecha");
        jPanel1.add(lblFecha_f, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        lblEstatus.setText("estatus");
        jPanel1.add(lblEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jPanel1.add(comboEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 160, -1));

        jLabel12.setText("Nombre:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel13.setText("Tipo de pieza:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        lblPieza.setText("pieza");
        jPanel1.add(lblPieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        lblTipoPieza.setText("tipo");
        jPanel1.add(lblTipoPieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel14.setText("Id Avion:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        lblIdAvion.setText("avion");
        jPanel1.add(lblIdAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 682, 642));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        Home ventana = new Home(nombreUsuario);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_HomeActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
           EnsamblajePieza ventana = new EnsamblajePieza(idAvionVentana,nombreUsuario);
           ventana.setLocationRelativeTo(null);
           ventana.setVisible(true);
           this.dispose(); 
    }//GEN-LAST:event_AtrasActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
     int validarFecha =2;
     DateFormat formatoFecha = new SimpleDateFormat ("yyyy-MM-dd");
      Date fecha_i = new Date();
      Date fecha_f = new Date();

        try {
         fecha_f =formatoFecha.parse(txtFecha_f.getText());
         fecha_i = formatoFecha.parse(lblFecha_i.getText());
         validarFecha=1;
} catch (Exception e) {
       
            validarFecha=0;
}
   if (validarFecha==1){
       if (nombreProceso.getText().equals("Ensamblaje")){
               if ( fecha_i.after(fecha_f) ){
           
                            JOptionPane.showMessageDialog(null, " La fecha Final no puede ser menor que la inicial " , "  Error", JOptionPane.ERROR_MESSAGE);
                }
                if ( fecha_i.before (fecha_f) && nombreProceso.getText().equals("Ensamblaje")){
                   control.modificarFechaFinalEnsamblajePieza(idProcesoActual,txtFecha_f.getText());
                   int idEnsamblajeAvion =control.devolverIdEnsamblajeAvionApartirIdEnsamblaje(idProcesoActual);
                   control.modificarFechaFinalEnsamblajeAvion(idEnsamblajeAvion);
                   JOptionPane.showMessageDialog(null, " Fecha Final " , "  Modificada", JOptionPane.INFORMATION_MESSAGE); 
//                   EnsamblajePieza ventana = new EnsamblajePieza(idAvionVentana);
//                   ventana.setLocationRelativeTo(null);
//                   ventana.setVisible(true);
//                   this.dispose(); 
                }
              
                if ( fecha_i.equals(fecha_f) ){
                   JOptionPane.showMessageDialog(null, " La fecha Final no puede ser  igual a la inicial " , " Error", JOptionPane.INFORMATION_MESSAGE); 
                } 
               if(comboEstatus.getSelectedItem().equals("finalizado") ){
                   String estatus_1=(String) comboEstatus.getSelectedItem();
                   control.modificarEstatusEmsablajePieza(idProcesoActual,estatus_1);
                   control.agregarPiezaArmada(idProcesoActual);
                   control.agregarPruebaPieza(idProcesoActual);
                   control.agregarUbicacionPiezas(idProcesoActual);
                   int idEnsamblajeAvion =control.devolverIdEnsamblajeAvionApartirIdEnsamblaje(idProcesoActual);
                   control.modificarFechaFinalEnsamblajeAvion(idEnsamblajeAvion);
                   int idPrueba= control.devolverIdPruebaPieza();
                   control.agregarPersonalPruebaPieza(idPrueba,"no",idProcesoActual);
                   control.modificarEncargadoPruebaPieza(idPrueba);
                   JOptionPane.showMessageDialog(null, " Se ha iniciado prueba de calidad id: "+idPrueba, "  Prueba Calidad", JOptionPane.INFORMATION_MESSAGE); 
                   EnsamblajePieza ventana = new EnsamblajePieza(idAvionVentana,nombreUsuario);
                   ventana.setLocationRelativeTo(null);
                   ventana.setVisible(true);
                   this.dispose(); 
                   
               }
             
       }
       else
          if (nombreProceso.getText().equals("Prueba")){
                if ( fecha_i.after(fecha_f) ){
           
                            JOptionPane.showMessageDialog(null, " La fecha Final no puede ser menor que la inicial " , "  Error", JOptionPane.ERROR_MESSAGE);
                }
               
                if ( fecha_i.before (fecha_f) && nombreProceso.getText().equals("Prueba")){
                  control.modificarFechaFinalPruebaPieza(idProcesoActual,txtFecha_f.getText());
                  int idEnsamblajeAvion =control.devolverIdEnsamblajeAvionApartirIdPruebaPieza(idProcesoActual);
             
                   control.modificarFechaFinalEnsamblajeAvion(idEnsamblajeAvion);
                   JOptionPane.showMessageDialog(null, " Fecha Final " , "  Modificada", JOptionPane.INFORMATION_MESSAGE); 
                 
                }
                if ( fecha_i.equals(fecha_f) ){
                   JOptionPane.showMessageDialog(null, " La fecha Final no puede ser  igual a la inicial " , " Error", JOptionPane.INFORMATION_MESSAGE); 
                } 
             
                if((comboEstatus.getSelectedItem().equals("satisfactorio") || comboEstatus.getSelectedItem().equals("insatisfactorio")) ){
                     String estatus_2=(String) comboEstatus.getSelectedItem();
                    control.modificarEstatusPruebaPieza(idProcesoActual,estatus_2);
                    JOptionPane.showMessageDialog(null, "Ah sido "+comboEstatus.getSelectedItem(),"La Prueba", JOptionPane.INFORMATION_MESSAGE); 
                          if  (comboEstatus.getSelectedItem().equals("satisfactorio")){ 
                               int modiAvi =control.modificarEstatusFinalAvion(idAvionVentana);                    
                    
                               if( modiAvi==1   ){
                      
                                int estausAvi=control.modificarEstausAvion(idAvionVentana);
                                 if (estausAvi==1)
                                    JOptionPane.showMessageDialog(null, "proceso de ensanblaje de Avion Id: "+idAvionVentana,"Finalizado", JOptionPane.INFORMATION_MESSAGE); 
                                  }
                          }
                          else
                              if (comboEstatus.getSelectedItem().equals("insatisfactorio"))
                              {  
                                
                                
//                                
                                   int idEnsamblaPiezaInsatisfactorio= control.devolverIdEnsamblajePiezaApartirDePrueba(idProcesoActual);// idProceso actual prueba
                                   control.agregarPruebaPiezaInsatisfactorio(idProcesoActual);
                                   control.agregarUbicacionPiezas(idEnsamblaPiezaInsatisfactorio);
                                   int idEnsamblajeAvion =control.devolverIdEnsamblajeAvionApartirIdEnsamblaje(idEnsamblaPiezaInsatisfactorio);
                                   control.modificarFechaFinalEnsamblajeAvion(idEnsamblajeAvion);
                                   int idPrueba= control.devolverIdPruebaPieza();
                                   control.agregarPersonalPruebaPieza(idPrueba,"no",idEnsamblaPiezaInsatisfactorio);
                                   control.modificarEncargadoPruebaPieza(idPrueba);
                                   JOptionPane.showMessageDialog(null, "Se ha ordenado una nuvea Prueba al  "+lblTipoPieza.getText()+"\n"+" Id de la Prueba: "+idPrueba,"La Prueba Ha si Insatisfactoria", JOptionPane.INFORMATION_MESSAGE); 
                                      
                                    
                                      
                              }
                                       EnsamblajePieza ventana = new EnsamblajePieza(idAvionVentana,nombreUsuario);
                                       ventana.setLocationRelativeTo(null);
                                       ventana.setVisible(true);
                                       this.dispose(); 

                            
                }
           }
   }
   else{
       JOptionPane.showMessageDialog(null, "Formato incorrecto de fecha" , " Error", JOptionPane.ERROR_MESSAGE);
       txtFecha_f.setText(lblFecha_f.getText());
   }
    }//GEN-LAST:event_guardarActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetallesProcesoPieza1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetallesProcesoPieza1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetallesProcesoPieza1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetallesProcesoPieza1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetallesProcesoPieza1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton Home;
    private javax.swing.JLabel cedula;
    private javax.swing.JComboBox<String> comboEstatus;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel idProceso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblEstatus;
    private javax.swing.JLabel lblFecha_f;
    private javax.swing.JLabel lblFecha_i;
    private javax.swing.JLabel lblIdAvion;
    private javax.swing.JLabel lblPieza;
    private javax.swing.JLabel lblTipoPieza;
    private javax.swing.JLabel nombreEncargado;
    private javax.swing.JLabel nombrePlanta;
    private javax.swing.JLabel nombreProceso;
    private javax.swing.JTable tablaPersonal;
    private javax.swing.JLabel telefono;
    private javax.swing.JTextField txtFecha_f;
    // End of variables declaration//GEN-END:variables
}
