/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import controller.Controladora;
import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author GREGORIO-PC
 */
public class EnsamblajePieza extends javax.swing.JFrame {
Controladora control = new Controladora();
int idAvionVentana;
String nombreUsuario="";
    /**
     * Creates new form EnsamblajePieza
     */
    public EnsamblajePieza() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false); 
//        control.llenarTablaEnsamblajeAvion(jTable1);
    }
    public EnsamblajePieza(int id_avion,String nombreUsuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false); 
        control.llenarTabalaEnsamblajePrueba(id_avion,jTable1);
        control.llenarVentaEnsamblajePieza(lblIdAvion, id_avion);
//        control.llenarComboEstatusPruebaTodo(comboEstatus);
        idAvionVentana=id_avion;
        comboEstatus.setEnabled(false);
        lblEstaus.setEnabled(false);
        this.nombreUsuario=nombreUsuario;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboPlanta = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        comboProceso = new javax.swing.JComboBox<>();
        atras = new javax.swing.JButton();
        home = new javax.swing.JButton();
        lblPrueba = new javax.swing.JLabel();
        Prueba = new javax.swing.JButton();
        txtPrueba = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblIdAvion = new javax.swing.JLabel();
        lblEnsamblaje = new javax.swing.JLabel();
        txtEnsamblaje = new javax.swing.JTextField();
        ensamblaje = new javax.swing.JButton();
        comboEstatus = new javax.swing.JComboBox<>();
        lblEstaus = new javax.swing.JLabel();

        jLabel6.setText("Planta :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Detalles del Ensamblaje de un Avion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id del Proceso", "Tipo", "Nombre", "fecha inicio ", "Fecha final ", "Estatus", "Planta", "Zona"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 680, 220));

        jLabel2.setText("Proceso :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, 20));

        comboProceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todo", "Prueba", "Ensamblaje" }));
        comboProceso.setToolTipText("");
        comboProceso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboProcesoItemStateChanged(evt);
            }
        });
        comboProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProcesoActionPerformed(evt);
            }
        });
        getContentPane().add(comboProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 150, 30));

        atras.setText("Atras");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblPrueba.setText("Id del la Prueba:");
        getContentPane().add(lblPrueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, -1));

        Prueba.setText("Prueba");
        Prueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PruebaActionPerformed(evt);
            }
        });
        getContentPane().add(Prueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));
        getContentPane().add(txtPrueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 90, -1));

        jLabel4.setText("Id del Avión:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        lblIdAvion.setText("90");
        getContentPane().add(lblIdAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        lblEnsamblaje.setText("Id del Ensamblaje:");
        getContentPane().add(lblEnsamblaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, -1));
        getContentPane().add(txtEnsamblaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 100, -1));

        ensamblaje.setText("Ensamblaje");
        ensamblaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ensamblajeActionPerformed(evt);
            }
        });
        getContentPane().add(ensamblaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, -1, -1));

        comboEstatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboEstatusItemStateChanged(evt);
            }
        });
        getContentPane().add(comboEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 150, -1));

        lblEstaus.setText("Estatus:");
        getContentPane().add(lblEstaus, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        Home ventana = new Home(nombreUsuario);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        EnsamblajeAvión ventana = new EnsamblajeAvión(nombreUsuario);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_atrasActionPerformed

    private void PruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PruebaActionPerformed
     
try {
      int   encontrePrueba=  control.buscarPruebaPieza(Integer.parseInt(txtPrueba.getText()));
        if (encontrePrueba == 1){
            JOptionPane.showMessageDialog(null, " Id Prueba: " + txtPrueba.getText(), "  ENCONTRADO", JOptionPane.INFORMATION_MESSAGE); 
            DetallesProcesoPieza1 ventana = new DetallesProcesoPieza1(Integer.parseInt(txtPrueba.getText()),idAvionVentana,"Prueba",nombreUsuario);
            ventana.setLocationRelativeTo(null);
            ventana.setVisible(true);
            this.dispose(); 
        }
        else
             if (encontrePrueba !=1){
                    JOptionPane.showMessageDialog(null, "Id Prueba: " + txtPrueba.getText(), " NO ENCONTRADO", JOptionPane.ERROR_MESSAGE); 
                    txtPrueba.setText(""); 
                 }
}
catch(Exception e){
             JOptionPane.showMessageDialog(null, "Ah ocurrido un error ", "Error", JOptionPane.ERROR_MESSAGE); 
               txtPrueba.setText(""); 
        }
        
            
            
    }//GEN-LAST:event_PruebaActionPerformed

    private void comboProcesoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboProcesoItemStateChanged
         if (evt.getStateChange()== ItemEvent.SELECTED)
            if ( comboProceso.getSelectedItem().equals("Todo")){
                            comboEstatus.setEnabled(false);
                     lblEstaus.setEnabled(false);
//                 control.llenarComboEstausTodo(comboEstatus);
                 control.llenarTabalaEnsamblajePrueba(idAvionVentana,jTable1);
                  ensamblaje.setEnabled(true);
                  txtEnsamblaje.setEnabled(true);
                  lblEnsamblaje.setEnabled(true);
                  Prueba.setEnabled(true);
                  txtPrueba.setEnabled(true);
                  lblPrueba.setEnabled(true);
                  
            }
            else
                 if ( comboProceso.getSelectedItem().equals("Prueba")){
                     comboEstatus.setEnabled(true);
                     lblEstaus.setEnabled(true);
                     control.llenarComboEstatusPruebaTodo(comboEstatus);
                     control.llenarTabalaPruebaPieza(idAvionVentana,jTable1);
                     ensamblaje.setEnabled(false);
                     txtEnsamblaje.setEnabled(false);
                     lblEnsamblaje.setEnabled(false);
                     Prueba.setEnabled(true);
                     txtPrueba.setEnabled(true);
                     lblPrueba.setEnabled(true);
                 }
         else
                  if ( comboProceso.getSelectedItem().equals("Ensamblaje")){
                     comboEstatus.setEnabled(true);
                     lblEstaus.setEnabled(true);
                     control.llenarComboEstatusPiezaTodo(comboEstatus);
                     control.llenarTabalaEnsamblajePieza(idAvionVentana, jTable1);
                     Prueba.setEnabled(false);
                     txtPrueba.setEnabled(false);
                     lblPrueba.setEnabled(false);
                     ensamblaje.setEnabled(true);
                     txtEnsamblaje.setEnabled(true);
                      lblEnsamblaje.setEnabled(true);
                  }
    }//GEN-LAST:event_comboProcesoItemStateChanged

    private void comboEstatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboEstatusItemStateChanged
        if (evt.getStateChange()== ItemEvent.SELECTED)
          
           
                 if ( comboProceso.getSelectedItem().equals("Prueba") ){
                       if ( comboEstatus.getSelectedItem().equals("Todo") )
                           control.llenarTabalaPruebaPieza(idAvionVentana,jTable1);
                       else
                         control.llenarTabalaPruebaPiezaEstatus(idAvionVentana,jTable1, (String) comboEstatus.getSelectedItem());
                 }
         else
                  if ( comboProceso.getSelectedItem().equals("Ensamblaje")){
                     if ( comboEstatus.getSelectedItem().equals("Todo") )
                          control.llenarTabalaEnsamblajePieza(idAvionVentana, jTable1);
                     else
                       control.llenarTabalaEnsamblajePiezaEstatus(idAvionVentana, jTable1, (String) comboEstatus.getSelectedItem());
                     
                  }
    }//GEN-LAST:event_comboEstatusItemStateChanged

    private void ensamblajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ensamblajeActionPerformed
    try{     
        int  encontreEnsamblaje = control.buscarEnsamblajePieza(Integer.parseInt(txtEnsamblaje.getText()));

        if (encontreEnsamblaje == 1){
            JOptionPane.showMessageDialog(null, " Id Ensamblaje: " + txtEnsamblaje.getText(), "  ENCONTRADO", JOptionPane.INFORMATION_MESSAGE); 
            DetallesProcesoPieza1 ventana = new DetallesProcesoPieza1(Integer.parseInt(txtEnsamblaje.getText()),idAvionVentana,"Ensamblaje",nombreUsuario);
            ventana.setLocationRelativeTo(null);
            ventana.setVisible(true);
            this.dispose(); 
        }
        else
             if (encontreEnsamblaje == 0){
                    JOptionPane.showMessageDialog(null, "Id Proceso: " + txtEnsamblaje.getText(), " NO ENCONTRADO", JOptionPane.ERROR_MESSAGE); 
                    txtEnsamblaje.setText(""); 
                 }
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, "Ah ocurrido un error ", "Error", JOptionPane.ERROR_MESSAGE);
         txtEnsamblaje.setText(""); 
    }
           
        
            
    }//GEN-LAST:event_ensamblajeActionPerformed

    private void comboProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProcesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboProcesoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnsamblajePieza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnsamblajePieza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnsamblajePieza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnsamblajePieza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnsamblajePieza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboPlanta;
    private javax.swing.JButton Prueba;
    private javax.swing.JButton atras;
    private javax.swing.JComboBox<String> comboEstatus;
    private javax.swing.JComboBox<String> comboProceso;
    private javax.swing.JButton ensamblaje;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblEnsamblaje;
    private javax.swing.JLabel lblEstaus;
    private javax.swing.JLabel lblIdAvion;
    private javax.swing.JLabel lblPrueba;
    private javax.swing.JTextField txtEnsamblaje;
    private javax.swing.JTextField txtPrueba;
    // End of variables declaration//GEN-END:variables
}
