/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

//import javaapplication2.Login;
import controller.Controladora;
import interfaz.EnsamblajeAvión;
import interfaz.ListarInventarioMaterial;
import interfaz.MenuModelo;
import interfaz.MenuPedidosCliente;
import interfaz.MenuRol;
import interfaz.Menu_Proveedores;
import interfaz.Menu_Usuario;
import interfaz.Menu_cliente;
import interfaz.Menu_pedidos_proveedor;
import interfaz.Pruebas_materiales;
import interfaz.Reportes;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author GREGORIO-PC
 */
public class Home extends javax.swing.JFrame {
    Controladora control = new Controladora();
    String nombreUsuario="";
   
  
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
       
        this.setLocationRelativeTo(null);
        this.setResizable(false); 
         
    
       
    }
     public Home(String nombreUsuario) {
        initComponents();       
        this.setLocationRelativeTo(null);
        this.setResizable(false); 
        this.nombreUsuario=nombreUsuario;  
        inventario.setVisible(false);
        lblUsuario.setText(nombreUsuario);
    
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonClienteHome = new javax.swing.JButton();
        botonProveedorHome = new javax.swing.JButton();
        botonAvionHome = new javax.swing.JButton();
        botonModelo = new javax.swing.JButton();
        pedidoCliente = new javax.swing.JButton();
        inventario = new javax.swing.JButton();
        pedidoProvvedor = new javax.swing.JButton();
        pruebaMateriales = new javax.swing.JButton();
        usuario = new javax.swing.JButton();
        rol = new javax.swing.JButton();
        inicio_secion = new javax.swing.JButton();
        reporte = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("HOME");

        botonClienteHome.setText("Clientes");
        botonClienteHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClienteHomeActionPerformed(evt);
            }
        });

        botonProveedorHome.setText("Proveedores");
        botonProveedorHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProveedorHomeActionPerformed(evt);
            }
        });

        botonAvionHome.setText("Aviones");
        botonAvionHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAvionHomeActionPerformed(evt);
            }
        });

        botonModelo.setText("Modelo de Avión");
        botonModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModeloActionPerformed(evt);
            }
        });

        pedidoCliente.setText("Pedidos del Cliente");
        pedidoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidoClienteActionPerformed(evt);
            }
        });

        inventario.setText("Inventario");
        inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioActionPerformed(evt);
            }
        });

        pedidoProvvedor.setText("Pedidos del Proveedor");
        pedidoProvvedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedidoProvvedorActionPerformed(evt);
            }
        });

        pruebaMateriales.setText("Pruebas de Materiales");
        pruebaMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pruebaMaterialesActionPerformed(evt);
            }
        });

        usuario.setText("Usuario");
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });

        rol.setText("Rol");
        rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolActionPerformed(evt);
            }
        });

        inicio_secion.setText("Inicio de Sesión");
        inicio_secion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicio_secionActionPerformed(evt);
            }
        });

        reporte.setText("Reportes");
        reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Usuario:");

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUsuario.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inicio_secion)
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblUsuario)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(rol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(botonClienteHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonProveedorHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pedidoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonModelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonAvionHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pedidoProvvedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pruebaMateriales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(48, 48, 48))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inicio_secion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblUsuario))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonProveedorHome)
                    .addComponent(usuario))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonClienteHome)
                    .addComponent(rol))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pedidoProvvedor)
                    .addComponent(reporte))
                .addGap(18, 18, 18)
                .addComponent(pedidoCliente)
                .addGap(28, 28, 28)
                .addComponent(botonModelo)
                .addGap(18, 18, 18)
                .addComponent(botonAvionHome)
                .addGap(18, 18, 18)
                .addComponent(pruebaMateriales)
                .addGap(18, 18, 18)
                .addComponent(inventario)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonProveedorHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProveedorHomeActionPerformed
    
        Menu_Proveedores ventana = new Menu_Proveedores(nombreUsuario);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
         
    
        
      
    }//GEN-LAST:event_botonProveedorHomeActionPerformed

    private void botonClienteHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClienteHomeActionPerformed
        
        Menu_cliente ventana = new Menu_cliente(nombreUsuario);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonClienteHomeActionPerformed

    private void botonModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModeloActionPerformed
        System.out.println("hola"+nombreUsuario);
        MenuModelo ventana = new MenuModelo(nombreUsuario);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonModeloActionPerformed

    private void botonAvionHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAvionHomeActionPerformed
    String  instruccion="consultar";
    String  nombreEntidad="avion"; 
     if (control.buscarPermiso(instruccion, nombreEntidad,nombreUsuario)==1){      
        EnsamblajeAvión ventana = new EnsamblajeAvión(nombreUsuario);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
     }
     else
          JOptionPane.showMessageDialog(null, "Su Usuario no tiene  el Privilegio  \n De Consultar los Aviones "  , "Acceso No Permitido", JOptionPane.ERROR_MESSAGE); 
    }//GEN-LAST:event_botonAvionHomeActionPerformed

    private void pedidoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidoClienteActionPerformed
          MenuPedidosCliente ventana = new MenuPedidosCliente(nombreUsuario);
          ventana.setLocationRelativeTo(null);
          ventana.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_pedidoClienteActionPerformed

    private void inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioActionPerformed
          ListarInventarioMaterial ventana = new ListarInventarioMaterial();
          ventana.setLocationRelativeTo(null);
          ventana.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_inventarioActionPerformed

    private void pedidoProvvedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedidoProvvedorActionPerformed
          Menu_pedidos_proveedor ventana = new Menu_pedidos_proveedor(nombreUsuario);
          ventana.setLocationRelativeTo(null);
          ventana.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_pedidoProvvedorActionPerformed

    private void pruebaMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pruebaMaterialesActionPerformed
    String  instruccion="consultar";
    String  nombreEntidad="prueba";

        if (control.buscarPermiso(instruccion, nombreEntidad,nombreUsuario)==1){         
            Pruebas_materiales ventana = new Pruebas_materiales(nombreUsuario);
             ventana.setLocationRelativeTo(null);
             ventana.setVisible(true);
             this.dispose();
        }
        else
            JOptionPane.showMessageDialog(null, "Su Usuario no tiene  el Privilegio  \n De Consultar las Pruebas de los materiales "  , "Acceso No Permitido", JOptionPane.ERROR_MESSAGE); 
    }//GEN-LAST:event_pruebaMaterialesActionPerformed

    private void rolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolActionPerformed
     
           MenuRol ventana = new MenuRol(nombreUsuario);
           ventana.setLocationRelativeTo(null);
           ventana.setVisible(true);
           this.dispose(); 
      
           
    }//GEN-LAST:event_rolActionPerformed

    private void inicio_secionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicio_secionActionPerformed
        Login ventana = new Login();
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_inicio_secionActionPerformed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
    
          Menu_Usuario ventana = new Menu_Usuario(nombreUsuario);
          ventana.setLocationRelativeTo(null);
          ventana.setVisible(true);
          this.dispose(); 
       
    
    }//GEN-LAST:event_usuarioActionPerformed

    private void reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteActionPerformed
        Reportes ventana = new Reportes(nombreUsuario);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAvionHome;
    private javax.swing.JButton botonClienteHome;
    private javax.swing.JButton botonModelo;
    private javax.swing.JButton botonProveedorHome;
    private javax.swing.JButton inicio_secion;
    private javax.swing.JButton inventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JButton pedidoCliente;
    private javax.swing.JButton pedidoProvvedor;
    private javax.swing.JButton pruebaMateriales;
    private javax.swing.JButton reporte;
    private javax.swing.JButton rol;
    private javax.swing.JButton usuario;
    // End of variables declaration//GEN-END:variables
}
