/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;


import controller.Controladora;
import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author GREGORIO-PC
 */
public class ListarPedidosClienteNueva extends javax.swing.JFrame {
Controladora control = new Controladora();
String nombreUsuario="";
String nombreEntidad="pedido_cliente";
String instruccion="modificar";
    /**
     * Creates new form ListarPedidosClienteNueva
     */
    public ListarPedidosClienteNueva() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        control.llenarComboClientePedido(comboCliente);
        control.llenarTablaListarPedidosClientes(jTable1);
        
    }
    public ListarPedidosClienteNueva(String nombreUsuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        control.llenarComboClientePedido(comboCliente);
        control.llenarTablaListarPedidosClientes(jTable1);
        this.nombreUsuario=nombreUsuario;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        atras = new javax.swing.JButton();
        detallar = new javax.swing.JButton();
        empresa = new javax.swing.JLabel();
        txtPedido = new javax.swing.JTextField();
        comboCliente = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, -1, 40));

        jLabel1.setText("ID del Pedido:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, -1));

        Titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Titulo.setText("Listar Pedidos del Clientes");
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id del pedidio", "Cliente", "Modelo", "Precio", "Fecha de pedido", "Estatus de Ensamblaje", "Fecha Pago"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 110, 980, 200));

        atras.setText("Atras");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        detallar.setText("Pagar");
        detallar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detallarActionPerformed(evt);
            }
        });
        jPanel1.add(detallar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));

        empresa.setText("Cliente:");
        jPanel1.add(empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));
        jPanel1.add(txtPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 90, -1));

        comboCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboClienteItemStateChanged(evt);
            }
        });
        jPanel1.add(comboCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1009, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        Home ventana = new Home(nombreUsuario);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        MenuPedidosCliente ventana = new MenuPedidosCliente(nombreUsuario);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_atrasActionPerformed

    private void comboClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboClienteItemStateChanged
          if (evt.getStateChange()== ItemEvent.SELECTED)  
              if ( comboCliente.getSelectedItem().equals("Todos")){
                  control.llenarTablaListarPedidosClientes(jTable1);
              }
          else
               
                  control.llenarTablaListarPedidosClientesPorNombre(jTable1, (String) comboCliente.getSelectedItem());
                
    }//GEN-LAST:event_comboClienteItemStateChanged

    private void detallarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detallarActionPerformed
      try{
            int permiso=0;
      if (control.buscarPermiso(instruccion, nombreEntidad,nombreUsuario)==1){
        int buscar= control.buscarPedidoClientePorPagar(Integer.parseInt(txtPedido.getText()));
      if (buscar ==1){
          
          JOptionPane.showMessageDialog(null, "Id Pedido: " + txtPedido.getText(), " ENCONTRADO", JOptionPane.INFORMATION_MESSAGE); 
           PagoCliente ventana = new PagoCliente(Integer.parseInt(txtPedido.getText()),nombreUsuario);
           ventana.setLocationRelativeTo(null);
           ventana.setVisible(true);
           this.dispose();
           
      }
      else
          JOptionPane.showMessageDialog(null, "Id Pedido: " + txtPedido.getText(), "No ENCONTRADO O NO DISPONIBLE PARA PAGAR", JOptionPane.INFORMATION_MESSAGE); 
      }
      else
           JOptionPane.showMessageDialog(null, "Acceso No Permitido "  , "Su Usuario no tiene este Privilegio ", JOptionPane.ERROR_MESSAGE); 
      }catch(Exception e){
          JOptionPane.showMessageDialog(null, "Ha ocurrido un error", "Error", JOptionPane.ERROR_MESSAGE); 
      }
          
    }//GEN-LAST:event_detallarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarPedidosClienteNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarPedidosClienteNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarPedidosClienteNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarPedidosClienteNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarPedidosClienteNueva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton atras;
    private javax.swing.JComboBox<String> comboCliente;
    private javax.swing.JButton detallar;
    private javax.swing.JLabel empresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtPedido;
    // End of variables declaration//GEN-END:variables
}
