/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import controller.Controladora;
import controller.Validacion;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author Fabian Graterol
 */
public class ModificarModelo extends javax.swing.JFrame {
Controladora control = new Controladora();
String nombreUsuario="";
String nombreActual;
String nombreEntidad="modelo";
String instruccion="modificar";
    /**
     * Creates new form Modelo_avion
     */
    public ModificarModelo() {
        initComponents();
             
        this.setLocationRelativeTo(null);
        this.setResizable(false); 
    }
public ModificarModelo(String nombre_1) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false); 
        control.llenarVentaModificarModelo(nombre_1, nombre,num_denasa,num_estandar,num_piloto,num_copiloto,num_auxiliar,distancia_aiento_densa,distancia_asiento_estandar,ancho_asiento,longitud,envargadura,altura,flecha_alar,ancho_fuselaje,alto_fuselaje,ancho_cabina,ancho_cabina_pasajero,peso_vacio,peso_max_despegue,peso_aterrizaje_max,volumen_carga,carrera_despegue_peso_max,techo_servicio,velocidad_crucero,velecidad_max,alcance_carga_max,max_combustible, empuje_max, empuje_velociadad_crucero,diametro_aspas,longitud_motor,empuje_unitario);
        nombreActual= nombre_1;
    }
public ModificarModelo(String nombre_1,String nombreUsuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false); 
        control.llenarVentaModificarModelo(nombre_1, nombre,num_denasa,num_estandar,num_piloto,num_copiloto,num_auxiliar,distancia_aiento_densa,distancia_asiento_estandar,ancho_asiento,longitud,envargadura,altura,flecha_alar,ancho_fuselaje,alto_fuselaje,ancho_cabina,ancho_cabina_pasajero,peso_vacio,peso_max_despegue,peso_aterrizaje_max,volumen_carga,carrera_despegue_peso_max,techo_servicio,velocidad_crucero,velecidad_max,alcance_carga_max,max_combustible, empuje_max, empuje_velociadad_crucero,diametro_aspas,longitud_motor,empuje_unitario);
        nombreActual= nombre_1;
        this.nombreUsuario=nombreUsuario;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Home = new javax.swing.JButton();
        atrasMdodelo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        num_denasa = new javax.swing.JTextField();
        num_estandar = new javax.swing.JTextField();
        num_piloto = new javax.swing.JTextField();
        num_copiloto = new javax.swing.JTextField();
        num_auxiliar = new javax.swing.JTextField();
        distancia_aiento_densa = new javax.swing.JTextField();
        peso_vacio = new javax.swing.JTextField();
        peso_max_despegue = new javax.swing.JTextField();
        peso_aterrizaje_max = new javax.swing.JTextField();
        volumen_carga = new javax.swing.JTextField();
        carrera_despegue_peso_max = new javax.swing.JTextField();
        techo_servicio = new javax.swing.JTextField();
        distancia_asiento_estandar = new javax.swing.JTextField();
        diametro_aspas = new javax.swing.JTextField();
        max_combustible = new javax.swing.JTextField();
        velecidad_max = new javax.swing.JTextField();
        empuje_velociadad_crucero = new javax.swing.JTextField();
        empuje_max = new javax.swing.JTextField();
        velocidad_crucero = new javax.swing.JTextField();
        alcance_carga_max = new javax.swing.JTextField();
        ancho_asiento = new javax.swing.JTextField();
        longitud = new javax.swing.JTextField();
        altura = new javax.swing.JTextField();
        flecha_alar = new javax.swing.JTextField();
        envargadura = new javax.swing.JTextField();
        ancho_fuselaje = new javax.swing.JTextField();
        alto_fuselaje = new javax.swing.JTextField();
        ancho_cabina = new javax.swing.JTextField();
        ancho_cabina_pasajero = new javax.swing.JTextField();
        longitud_motor = new javax.swing.JTextField();
        empuje_unitario = new javax.swing.JTextField();
        modificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Titulo.setText("Modificar modelo de avion");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 17, -1, -1));

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        getContentPane().add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 40));

        atrasMdodelo.setText("Atras");
        atrasMdodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasMdodeloActionPerformed(evt);
            }
        });
        getContentPane().add(atrasMdodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));

        jLabel1.setText("Modelo: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 99, -1, -1));

        jLabel2.setText("Numero de pasajeros denso: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel3.setText("Distancia entre asientos estandar:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 278, -1, -1));

        jLabel4.setText("Pasajeros en clase estandar:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 148, -1, -1));

        jLabel5.setText("Capacidad de copilotos: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 200, -1, -1));

        jLabel6.setText("Capacidad de pilotos: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 174, -1, -1));

        jLabel7.setText("Capacidad de auxiliares: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 226, -1, -1));

        jLabel8.setText("Distancia entre asientos densa:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 252, -1, -1));

        jLabel9.setText("Ancho de un asiento: ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 309, -1, -1));

        jLabel10.setText("Longitud de un avion: ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 335, -1, -1));

        jLabel11.setText("Longitud de la envargadura: ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 361, -1, -1));

        jLabel12.setText("Altura maxima: ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 387, -1, -1));

        jLabel13.setText("Angulo de flecha alar: ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 413, -1, -1));

        jLabel14.setText("Ancho del fuselaje: ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 439, -1, -1));

        jLabel15.setText("Alto del fuselaje: ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 465, -1, -1));

        jLabel16.setText("Ancho de cabina de piloto: ");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 491, -1, -1));

        jLabel17.setText("Ancho de cabina de pasajeros: ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 517, -1, -1));

        jLabel18.setText("Max del peso vacio: ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 96, -1, -1));

        jLabel19.setText("Peso máximo al despegar (Kg): ");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 122, -1, -1));

        jLabel20.setText("Peso máximo al aterrizar(Kg): ");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 148, -1, -1));

        jLabel21.setText("Volumen máximo de carga: ");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 177, -1, -1));

        jLabel22.setText("Peso max en carrera(Kg):");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 203, -1, -1));

        jLabel23.setText("Longitud de techo de servicio: ");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 226, -1, -1));

        jLabel24.setText("Velocidad del crucero: ");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 249, -1, -1));

        jLabel25.setText("Velocidad máxima: ");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 275, -1, -1));

        jLabel26.setText("Alcance máximo de carga: ");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 301, -1, -1));

        jLabel27.setText("Máximo de combustible: ");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 327, -1, -1));

        jLabel28.setText("Magnitud del empuje max: ");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 350, -1, -1));

        jLabel29.setText("Velocidad del empuje del crucero: ");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 379, -1, -1));

        jLabel30.setText("Diametro de aspas: ");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 405, -1, -1));

        jLabel31.setText("Longitud del motor: ");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 431, -1, -1));

        jLabel32.setText("Magnitud del empuje unitario: ");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 457, -1, -1));
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 93, 99, -1));
        getContentPane().add(num_denasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 119, 99, -1));
        getContentPane().add(num_estandar, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 145, 99, -1));
        getContentPane().add(num_piloto, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 171, 99, -1));
        getContentPane().add(num_copiloto, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 197, 99, -1));
        getContentPane().add(num_auxiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 223, 99, -1));
        getContentPane().add(distancia_aiento_densa, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 249, 99, -1));
        getContentPane().add(peso_vacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 93, 99, -1));
        getContentPane().add(peso_max_despegue, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 119, 99, -1));
        getContentPane().add(peso_aterrizaje_max, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 145, 99, -1));
        getContentPane().add(volumen_carga, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 174, 99, -1));
        getContentPane().add(carrera_despegue_peso_max, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 200, 99, -1));
        getContentPane().add(techo_servicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 223, 99, -1));
        getContentPane().add(distancia_asiento_estandar, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 275, 99, -1));
        getContentPane().add(diametro_aspas, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 402, 99, -1));
        getContentPane().add(max_combustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 324, 99, -1));
        getContentPane().add(velecidad_max, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 272, 99, -1));
        getContentPane().add(empuje_velociadad_crucero, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 376, 99, -1));

        empuje_max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empuje_maxActionPerformed(evt);
            }
        });
        getContentPane().add(empuje_max, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 350, 99, -1));
        getContentPane().add(velocidad_crucero, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 246, 99, -1));
        getContentPane().add(alcance_carga_max, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 298, 99, -1));
        getContentPane().add(ancho_asiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 306, 99, -1));
        getContentPane().add(longitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 332, 99, -1));
        getContentPane().add(altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 384, 99, -1));
        getContentPane().add(flecha_alar, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 410, 99, -1));
        getContentPane().add(envargadura, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 358, 99, -1));
        getContentPane().add(ancho_fuselaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 436, 99, -1));
        getContentPane().add(alto_fuselaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 462, 99, -1));
        getContentPane().add(ancho_cabina, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 488, 99, -1));
        getContentPane().add(ancho_cabina_pasajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 514, 99, -1));
        getContentPane().add(longitud_motor, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 428, 99, -1));
        getContentPane().add(empuje_unitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 454, 99, -1));

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
       Home ventana = new Home(nombreUsuario);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_HomeActionPerformed

    private void atrasMdodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasMdodeloActionPerformed
                 MenuModelo ventana = new MenuModelo(nombreUsuario);
                 ventana.setLocationRelativeTo(null);
                 ventana.setVisible(true);
                 this.dispose();        
    }//GEN-LAST:event_atrasMdodeloActionPerformed

    private void empuje_maxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empuje_maxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empuje_maxActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed

      int verificarModificar;
        int permiso=0;
      if (control.buscarPermiso(instruccion, nombreEntidad,nombreUsuario)==1){
        if (("".equals(nombre.getText())) == false){
               if (control.buscarModelo(nombre.getText())!= 1 ){
                      
                       
                        verificarModificar= control.modificarModelo(nombreActual,nombre.getText(),num_denasa.getText(),num_estandar.getText(),num_piloto.getText(),num_copiloto.getText(),num_auxiliar.getText(),distancia_aiento_densa.getText(),distancia_asiento_estandar.getText(),ancho_asiento.getText(),longitud.getText(),envargadura.getText(),altura.getText(),flecha_alar.getText(),ancho_fuselaje.getText(),alto_fuselaje.getText(),ancho_cabina.getText(),ancho_cabina_pasajero.getText(),peso_vacio.getText(),peso_max_despegue.getText(),peso_aterrizaje_max.getText(),carrera_despegue_peso_max.getText(),carrera_despegue_peso_max.getText(),techo_servicio.getText(),velocidad_crucero.getText(),velecidad_max.getText(),alcance_carga_max.getText(),max_combustible.getText(),empuje_max.getText(),empuje_velociadad_crucero.getText(),diametro_aspas.getText(),longitud_motor.getText(),empuje_unitario.getText());
                         if (verificarModificar == 1){
                          JOptionPane.showMessageDialog(null, "Modelo " + nombre.getText(), " modificado con exito!", JOptionPane.INFORMATION_MESSAGE);
                              MenuModelo ventana = new MenuModelo(nombreUsuario);
                              ventana.setLocationRelativeTo(null);
                              ventana.setVisible(true);
                              this.dispose();    
       
                         }
                         else
                              if (verificarModificar == 0){
                              JOptionPane.showMessageDialog(null, "Modelo " + nombre.getText(), " No se pudo modifcar!", JOptionPane.ERROR_MESSAGE);
                              MenuModelo ventana = new MenuModelo(nombreUsuario);
                              ventana.setLocationRelativeTo(null);
                              ventana.setVisible(true);
                              this.dispose();    
                              }
               }
               else{
                   
           
                    if ((control.devolverModelo(nombre.getText())).equals(nombreActual)){ 
                          verificarModificar= control.modificarModelo(nombreActual,nombre.getText(),num_denasa.getText(),num_estandar.getText(),num_piloto.getText(),num_copiloto.getText(),num_auxiliar.getText(),distancia_aiento_densa.getText(),distancia_asiento_estandar.getText(),ancho_asiento.getText(),longitud.getText(),envargadura.getText(),altura.getText(),flecha_alar.getText(),ancho_fuselaje.getText(),alto_fuselaje.getText(),ancho_cabina.getText(),ancho_cabina_pasajero.getText(),peso_vacio.getText(),peso_max_despegue.getText(),peso_aterrizaje_max.getText(),carrera_despegue_peso_max.getText(),carrera_despegue_peso_max.getText(),techo_servicio.getText(),velocidad_crucero.getText(),velecidad_max.getText(),alcance_carga_max.getText(),max_combustible.getText(),empuje_max.getText(),empuje_velociadad_crucero.getText(),diametro_aspas.getText(),longitud_motor.getText(),empuje_unitario.getText());
                         if (verificarModificar == 1){
                          JOptionPane.showMessageDialog(null, "Modelo " + nombre.getText(), " modificado con exito!", JOptionPane.INFORMATION_MESSAGE);
                              MenuModelo ventana = new MenuModelo(nombreUsuario);
                              ventana.setLocationRelativeTo(null);
                              ventana.setVisible(true);
                              this.dispose();    
       
                         }
                         else
                              if (verificarModificar == 0){
                              JOptionPane.showMessageDialog(null, "Modelo " + nombre.getText(), " No se pudo modifcar!", JOptionPane.ERROR_MESSAGE);
                              MenuModelo ventana = new MenuModelo(nombreUsuario);
                              ventana.setLocationRelativeTo(null);
                              ventana.setVisible(true);
                              this.dispose();    
                              }
                
             }
                    else
                       JOptionPane.showMessageDialog(null, "Modelo" , " Modelo ya registrada!", JOptionPane.ERROR_MESSAGE);
                   
                   
               }
            
        }
       else
          JOptionPane.showMessageDialog(null, "ERROR "  , " el nombre del modelo se debe llenar!", JOptionPane.ERROR_MESSAGE);
      } else
         JOptionPane.showMessageDialog(null, "Acceso No Permitido "  , "Su Usuario no tiene este Privilegio ", JOptionPane.ERROR_MESSAGE); 
    }//GEN-LAST:event_modificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarModelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarModelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarModelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarModelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarModelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField alcance_carga_max;
    private javax.swing.JTextField alto_fuselaje;
    private javax.swing.JTextField altura;
    private javax.swing.JTextField ancho_asiento;
    private javax.swing.JTextField ancho_cabina;
    private javax.swing.JTextField ancho_cabina_pasajero;
    private javax.swing.JTextField ancho_fuselaje;
    private javax.swing.JButton atrasMdodelo;
    private javax.swing.JTextField carrera_despegue_peso_max;
    private javax.swing.JTextField diametro_aspas;
    private javax.swing.JTextField distancia_aiento_densa;
    private javax.swing.JTextField distancia_asiento_estandar;
    private javax.swing.JTextField empuje_max;
    private javax.swing.JTextField empuje_unitario;
    private javax.swing.JTextField empuje_velociadad_crucero;
    private javax.swing.JTextField envargadura;
    private javax.swing.JTextField flecha_alar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField longitud;
    private javax.swing.JTextField longitud_motor;
    private javax.swing.JTextField max_combustible;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField num_auxiliar;
    private javax.swing.JTextField num_copiloto;
    private javax.swing.JTextField num_denasa;
    private javax.swing.JTextField num_estandar;
    private javax.swing.JTextField num_piloto;
    private javax.swing.JTextField peso_aterrizaje_max;
    private javax.swing.JTextField peso_max_despegue;
    private javax.swing.JTextField peso_vacio;
    private javax.swing.JTextField techo_servicio;
    private javax.swing.JTextField velecidad_max;
    private javax.swing.JTextField velocidad_crucero;
    private javax.swing.JTextField volumen_carga;
    // End of variables declaration//GEN-END:variables
}
