/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import controller.Controladora;
import java.awt.event.ItemEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;


public class PagosProveedor extends javax.swing.JFrame {
Controladora control =  new Controladora (); 
String nombreUsuario="";
    
    /**C
     * Creates new form SolicitudesProveedor
     */
    public PagosProveedor() {
        initComponents();
         
         this.setLocationRelativeTo(null);
        this.setResizable(false); 
        control.llenarTablaPago(tablaSolicitudes);
     pagoCombo.removeAllItems();
     
        pagoCombo.addItem("Seleccione Forma de Pago");
        pagoCombo.addItem("transferencia");
        pagoCombo.addItem("tarjeta");
        bancoTxt.setVisible(false);
        cuentaTxt.setVisible(false);
        transTxt.setVisible(false);
        jLabel4.setVisible(false);
        numC.setVisible(false);
       jLabel5.setVisible(false);
       calendar.setVisible(false);
    }
     public PagosProveedor(String nombreUsuario) {
        initComponents();
         
         this.setLocationRelativeTo(null);
        this.setResizable(false); 
        control.llenarTablaPago(tablaSolicitudes);
     pagoCombo.removeAllItems();
     
        pagoCombo.addItem("Seleccione Forma de Pago");
        pagoCombo.addItem("transferencia");
        pagoCombo.addItem("tarjeta");
        bancoTxt.setVisible(false);
        cuentaTxt.setVisible(false);
        transTxt.setVisible(false);
        jLabel4.setVisible(false);
        numC.setVisible(false);
       jLabel5.setVisible(false);
       calendar.setVisible(false);
     this.nombreUsuario=nombreUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSolicitudes = new javax.swing.JTable();
        Atras2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        IdTxt = new javax.swing.JTextField();
        pagar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pagoCombo = new javax.swing.JComboBox();
        bancoTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cuentaTxt = new javax.swing.JTextField();
        transTxt = new javax.swing.JTextField();
        numC = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        calendar = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Pagar Pedido");

        tablaSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Material"
            }
        ));
        jScrollPane1.setViewportView(tablaSolicitudes);

        Atras2.setText("Atrás");
        Atras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Atras2ActionPerformed(evt);
            }
        });

        jLabel2.setText("ID del pedido:");

        pagar.setText("Pagar");
        pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarActionPerformed(evt);
            }
        });

        jLabel3.setText("Forma de pago:");

        pagoCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pagoCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pagoComboItemStateChanged(evt);
            }
        });

        jLabel4.setText("Banco:");

        cuentaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentaTxtActionPerformed(evt);
            }
        });

        numC.setText("Número de cuenta:");

        jLabel5.setText("Numero de Transferencia:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Atras2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(numC)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bancoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addComponent(cuentaTxt))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(transTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pagar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pagoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(255, 255, 255))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(Atras2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(IdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pagoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(bancoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cuentaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numC))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(transTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pagar)
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Atras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Atras2ActionPerformed
        Menu_pedidos_proveedor ventana = new Menu_pedidos_proveedor(nombreUsuario);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Atras2ActionPerformed

    private void pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarActionPerformed
        //try {
  
      Date fecha = new Date ();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
         String date = sdf.format(fecha);
        
         
         
  int verificar = 0;       
        int ver ;
       if ( (pagoCombo.getSelectedItem().equals("transferencia")))  
               {
                   String monto = control.Devolvermonto(Integer.parseInt(IdTxt.getText()));
       ver = control.agregarFormaDePagomaterial(Integer.parseInt(IdTxt.getText()),pagoCombo.getSelectedItem().toString(), Integer.parseInt(transTxt.getText()), bancoTxt.getText(), Integer.parseInt(cuentaTxt.getText()), 0, null,monto);
        if (ver == 1) 
       verificar =  control.modificarFechadePago(Integer.parseInt(IdTxt.getText()), date);}
       else
       if ( (pagoCombo.getSelectedItem().equals("tarjeta"))){
           String data = sdf.format(calendar.getDate());
       String monto = control.Devolvermonto(Integer.parseInt(IdTxt.getText()));
       ver = control.agregarFormaDePagomaterial(Integer.parseInt(IdTxt.getText()),pagoCombo.getSelectedItem().toString(), 0, bancoTxt.getText(), 0,  Integer.parseInt(cuentaTxt.getText()), data,monto);
        if (ver == 1) 
       verificar =  control.modificarFechadePago(Integer.parseInt(IdTxt.getText()), date);}
      if (verificar == 1){
                    JOptionPane.showMessageDialog(null, "El pago se a realizado con éxito ", " Pago realizado", JOptionPane.INFORMATION_MESSAGE);
      control.llenarTablaPago(tablaSolicitudes);}
      else 
                  JOptionPane.showMessageDialog(null, "ERROR, pago fallido " , "ERROR", JOptionPane.ERROR_MESSAGE);

 //}
//catch(Exception e)
        //{
                 // JOptionPane.showMessageDialog(null, "ERROR, pago fallido " , "ERROR", JOptionPane.ERROR_MESSAGE);
            //
  //}                                     

     
    }//GEN-LAST:event_pagarActionPerformed

    private void cuentaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuentaTxtActionPerformed

    private void pagoComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pagoComboItemStateChanged

  if (evt.getStateChange()== ItemEvent.SELECTED)
       {
         if (pagoCombo.getSelectedItem().equals("transferencia")){
        bancoTxt.setVisible(true);
        cuentaTxt.setVisible(true);
        transTxt.setVisible(true);
        jLabel4.setVisible(true);
         calendar.setVisible(false);
            
            jLabel5.setText("Numero de transferencia");

            numC.setText("Numero de cuenta");

        numC.setVisible(true);
       jLabel5.setVisible(true);}
       else 
        if (pagoCombo.getSelectedItem().equals("tarjeta"))
        {
        bancoTxt.setVisible(true);
        jLabel4.setVisible(true);
        numC.setVisible(true);
        numC.setText("Numero de Tarjeta");
        transTxt.setVisible(false);
        jLabel5.setVisible(true);
            calendar.setVisible(true);
            cuentaTxt.setVisible(true);
            jLabel5.setText("Fecha de Vencimiento");

        }
       
       }
  

    }//GEN-LAST:event_pagoComboItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagosProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagosProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagosProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagosProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagosProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras2;
    private javax.swing.JTextField IdTxt;
    private javax.swing.JTextField bancoTxt;
    private com.toedter.calendar.JDateChooser calendar;
    private javax.swing.JTextField cuentaTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numC;
    private javax.swing.JButton pagar;
    private javax.swing.JComboBox pagoCombo;
    private javax.swing.JTable tablaSolicitudes;
    private javax.swing.JTextField transTxt;
    // End of variables declaration//GEN-END:variables
}
