/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import controller.Controladora;

import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;

public class Pruebas_materiales extends javax.swing.JFrame {
String nombreUsuario="";
Controladora control= new Controladora();
String planta="Todas";
String estatus="Todos";
    /**
     * Creates new form pruebas_materiales
     */
    public Pruebas_materiales() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false); 
        control.llenarPlantaBox(plantaCombo);
        plantaCombo.addItem("Todas");
        control.llenarEstatusBox(estatus_combo);
        estatus_combo.removeItem("finalizado");
        control.llenarTablaPruebas(tabla_prueba,"Todas","Todos");
        
    }
        public Pruebas_materiales(String nombreUsuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false); 
        control.llenarPlantaBox(plantaCombo);
        plantaCombo.addItem("Todas");
        control.llenarEstatusBox(estatus_combo);
        estatus_combo.removeItem("finalizado");
        control.llenarTablaPruebas(tabla_prueba,"Todas","Todos");
        this.nombreUsuario=nombreUsuario;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        id_text = new javax.swing.JTextField();
        Titulo = new javax.swing.JLabel();
        detallar = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_prueba = new javax.swing.JTable();
        plantaCombo = new javax.swing.JComboBox<>();
        estatus_combo = new javax.swing.JComboBox<>();

        Back.setText("Atras");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        id.setText("ID: ");

        Titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Titulo.setText("Pruebas de materiales");

        detallar.setText("Detallar");
        detallar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detallarActionPerformed(evt);
            }
        });

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        tabla_prueba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Fecha I", "Fecha F", "Fecha E", "Estatus"
            }
        ));
        jScrollPane1.setViewportView(tabla_prueba);
        if (tabla_prueba.getColumnModel().getColumnCount() > 0) {
            tabla_prueba.getColumnModel().getColumn(0).setMinWidth(50);
            tabla_prueba.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabla_prueba.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        plantaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        plantaCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                plantaComboItemStateChanged(evt);
            }
        });
        plantaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantaComboActionPerformed(evt);
            }
        });

        estatus_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        estatus_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                estatus_comboItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(plantaCombo, 0, 90, Short.MAX_VALUE)
                    .addComponent(estatus_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detallar)
                    .addComponent(id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(161, 161, 161))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Home)
                        .addGap(137, 137, 137)
                        .addComponent(Titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Titulo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plantaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id)
                    .addComponent(id_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detallar)
                    .addComponent(estatus_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        Home ventana = new Home(nombreUsuario);
          ventana.setLocationRelativeTo(null);
          ventana.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_HomeActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        Home ventana = new Home(nombreUsuario);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void plantaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantaComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plantaComboActionPerformed

    private void detallarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detallarActionPerformed
          if (id_text.getText().isEmpty()==false){
            Detalle_prueba_material ventana = new Detalle_prueba_material(Integer.parseInt(id_text.getText()),nombreUsuario);
            ventana.setLocationRelativeTo(null);
            ventana.setVisible(true);
            this.dispose();
    }else
              JOptionPane.showMessageDialog(null, "El ID no puede estar en blanco!", " Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_detallarActionPerformed

    private void plantaComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_plantaComboItemStateChanged

       if (evt.getStateChange()== ItemEvent.SELECTED)
            planta= plantaCombo.getSelectedItem().toString();
        if (planta.equals("Seleccione Planta"))
                planta="Todas";
        control.llenarTablaPruebas(tabla_prueba, planta,estatus);
       
             
    }//GEN-LAST:event_plantaComboItemStateChanged

    private void estatus_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_estatus_comboItemStateChanged
        if (evt.getStateChange()== ItemEvent.SELECTED){
                estatus= estatus_combo.getSelectedItem().toString();
            if (estatus.equals("Seleccione un estatus"))
                estatus="Todos";
            control.llenarTablaPruebas(tabla_prueba, planta,estatus);
        }
    }//GEN-LAST:event_estatus_comboItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pruebas_materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pruebas_materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pruebas_materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pruebas_materiales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pruebas_materiales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Home;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton detallar;
    private javax.swing.JComboBox<String> estatus_combo;
    private javax.swing.JLabel id;
    private javax.swing.JTextField id_text;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> plantaCombo;
    private javax.swing.JTable tabla_prueba;
    // End of variables declaration//GEN-END:variables
}
