/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;


import com.itextpdf.text.log.Logger;
import controller.Controladora;
import java.security.Principal;
import javax.swing.JOptionPane;
import sun.net.ftp.FtpReplyCode;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.eclipse.persistence.logging.SessionLog;

/**
 *
 * @author GREGORIO-PC
 */
public class Reportes extends javax.swing.JFrame {
    Controladora control = new Controladora();
    String nombreEntidad="";
    String instruccion="consultar";
    int permiso=0;
    String nombreUsuario="";
        public Reportes() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false); 
    
    }
    /**
     * Creates new form Reportes
     */
    public Reportes(String nombreUsuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false); 
        this.nombreUsuario=nombreUsuario;  
        jLabel21.setText(nombreUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        produccionAnual = new javax.swing.JButton();
        promedioDeProduccionMensual = new javax.swing.JButton();
        los10MejoresClientes = new javax.swing.JButton();
        evolucionAeronautica = new javax.swing.JButton();
        modeloAvion = new javax.swing.JButton();
        mediaAviones = new javax.swing.JButton();
        modeloMasVendido = new javax.swing.JButton();
        equipoMasEficiente = new javax.swing.JButton();
        inventarioMensual = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        tipoAla = new javax.swing.JButton();
        avionRentanble = new javax.swing.JButton();
        espicificacionModelo = new javax.swing.JButton();
        productoPruebaCalidad = new javax.swing.JButton();
        trasladoSedes = new javax.swing.JButton();
        ListarProveedor = new javax.swing.JButton();
        plantaEficiente = new javax.swing.JButton();
        descripcionPiezas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        atras = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Reportes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        produccionAnual.setText("Produccion Anual");
        produccionAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produccionAnualActionPerformed(evt);
            }
        });
        jPanel1.add(produccionAnual, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 230, -1));

        promedioDeProduccionMensual.setText("Promedio de Producción Mensual");
        promedioDeProduccionMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promedioDeProduccionMensualActionPerformed(evt);
            }
        });
        jPanel1.add(promedioDeProduccionMensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 230, -1));

        los10MejoresClientes.setText("Top 10 de los mejores Clientes Por Año");
        los10MejoresClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                los10MejoresClientesActionPerformed(evt);
            }
        });
        jPanel1.add(los10MejoresClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 230, -1));

        evolucionAeronautica.setText("Evolución Aeronautica");
        evolucionAeronautica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evolucionAeronauticaActionPerformed(evt);
            }
        });
        jPanel1.add(evolucionAeronautica, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 230, -1));

        modeloAvion.setText("Modelo de Aviones");
        modeloAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloAvionActionPerformed(evt);
            }
        });
        jPanel1.add(modeloAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 250, 230, -1));

        mediaAviones.setText("Cantidad Media de Aviones Producidas Mensualmente Por Modelo");
        mediaAviones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediaAvionesActionPerformed(evt);
            }
        });
        jPanel1.add(mediaAviones, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        modeloMasVendido.setText("Modelo Mas Vendido");
        modeloMasVendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloMasVendidoActionPerformed(evt);
            }
        });
        jPanel1.add(modeloMasVendido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 230, -1));

        equipoMasEficiente.setText("Equipo Mas Eficiente");
        equipoMasEficiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipoMasEficienteActionPerformed(evt);
            }
        });
        jPanel1.add(equipoMasEficiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 230, -1));

        inventarioMensual.setText("Inventario Mensual");
        inventarioMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioMensualActionPerformed(evt);
            }
        });
        jPanel1.add(inventarioMensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 230, -1));

        jButton10.setText("Producto Mas Pedido Al Inventario");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        tipoAla.setText("Tipo de Ala Mas Utilizada");
        tipoAla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoAlaActionPerformed(evt);
            }
        });
        jPanel1.add(tipoAla, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 200, -1));

        avionRentanble.setText("Aviones Mas Rentanbles");
        avionRentanble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avionRentanbleActionPerformed(evt);
            }
        });
        jPanel1.add(avionRentanble, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 200, -1));

        espicificacionModelo.setText("Espicificaciones del Modelo");
        espicificacionModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espicificacionModeloActionPerformed(evt);
            }
        });
        jPanel1.add(espicificacionModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 200, -1));

        productoPruebaCalidad.setText("Cantidad de Productos que No cumplieron Con la Prueba de Calidad");
        productoPruebaCalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoPruebaCalidadActionPerformed(evt);
            }
        });
        jPanel1.add(productoPruebaCalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 360, -1));

        trasladoSedes.setText("Promedio  de traslados Entre Las Sedes");
        trasladoSedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trasladoSedesActionPerformed(evt);
            }
        });
        jPanel1.add(trasladoSedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 260, -1));

        ListarProveedor.setText("Listado De Proveedores");
        ListarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(ListarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 220, -1));

        plantaEficiente.setText("Plantas Mas Eficiente En Base Al  Cumplimeinto de  las Fechas");
        plantaEficiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantaEficienteActionPerformed(evt);
            }
        });
        jPanel1.add(plantaEficiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 350, -1));

        descripcionPiezas.setText("Descripción De las Piezas");
        descripcionPiezas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcionPiezasActionPerformed(evt);
            }
        });
        jPanel1.add(descripcionPiezas, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 280, -1));

        jLabel2.setText("1)");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel3.setText("2)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel4.setText("3)");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel5.setText("4)");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel6.setText("5)");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 10));

        jLabel7.setText("6)");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel8.setText("7)");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel9.setText("8)");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jLabel10.setText("9)");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jLabel11.setText("10)");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));

        jLabel12.setText("11)");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));

        jLabel13.setText("12)");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, -1));

        jLabel14.setText("13)");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, -1, -1));

        jLabel15.setText("14)");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, -1, 20));

        jLabel16.setText("15)");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, -1, -1));

        jLabel17.setText("16)");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));

        jLabel18.setText("17)");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, -1, -1));

        jLabel19.setText("18)");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, -1, -1));

        atras.setText("Atrás");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Usuario:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("hjjhft");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mediaAvionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediaAvionesActionPerformed
        nombreEntidad="media de aviones";
        if (control.buscarPermiso(instruccion, nombreEntidad,nombreUsuario)==1){
         try{
                Connection conexion = control.conexion();
                
                JasperReport reporte;
                String path="C:\\Users\\GREGORIO-PC\\Documents\\NetBeansProjects\\airUcab\\build\\classes\\reporte\\MediaDeAviones.jasper";
                reporte=(JasperReport) JRLoader.loadObjectFromFile(path);

                JasperPrint jprint=JasperFillManager.fillReport(reporte,null, conexion);
                JasperViewer viewer=new JasperViewer(jprint,false);
                setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                viewer.setVisible(true);
                
            }
            catch(JRException e){
                System.out.println("Error");
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Su Usuario no tiene  el Privilegio  \n De Consultar la  Cantidad Media De Aviones"  , "Acceso No Permitido", JOptionPane.ERROR_MESSAGE); 
    }//GEN-LAST:event_mediaAvionesActionPerformed

    private void produccionAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produccionAnualActionPerformed
      
       nombreEntidad="produccion anual";
        if (control.buscarPermiso(instruccion, nombreEntidad,nombreUsuario)==1){
         ProduccionAnual ventana = new ProduccionAnual(nombreUsuario);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
        }
        else
            JOptionPane.showMessageDialog(null, "Su Usuario no tiene  el Privilegio  \n De Consultar la  Produccion Anual "  , "Acceso No Permitido", JOptionPane.ERROR_MESSAGE); 
    }//GEN-LAST:event_produccionAnualActionPerformed

    private void promedioDeProduccionMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promedioDeProduccionMensualActionPerformed
     
       nombreEntidad="promedio de produccion mensual";
        if (control.buscarPermiso(instruccion, nombreEntidad,nombreUsuario)==1){
         PromedioProduccionMensual ventana = new PromedioProduccionMensual(nombreUsuario);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
        }
        else
            JOptionPane.showMessageDialog(null, "Su Usuario no tiene  el Privilegio  \n De Consultar el Promedio De Produccion Mensual"  , "Acceso No Permitido", JOptionPane.ERROR_MESSAGE); 
    }//GEN-LAST:event_promedioDeProduccionMensualActionPerformed

    private void los10MejoresClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_los10MejoresClientesActionPerformed
   
       nombreEntidad="10 mejores clientes";
        if (control.buscarPermiso(instruccion, nombreEntidad,nombreUsuario)==1){
            
             AñoPedidoCliente ventana = new AñoPedidoCliente(nombreUsuario);
             ventana.setLocationRelativeTo(null);
             ventana.setVisible(true);
             this.dispose();
           
        }
        else
            JOptionPane.showMessageDialog(null, "Su Usuario no tiene  el Privilegio  \n De Consultar el Top 10 de los Mejores Clientes"  , "Acceso No Permitido", JOptionPane.ERROR_MESSAGE); 
    }//GEN-LAST:event_los10MejoresClientesActionPerformed

    private void evolucionAeronauticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evolucionAeronauticaActionPerformed
   
       nombreEntidad="evolucion aeronautica";
        if (control.buscarPermiso(instruccion, nombreEntidad,nombreUsuario)==1){
         try{
                Connection conexion = control.conexion();
                
                JasperReport reporte;
                String path="C:\\Users\\GREGORIO-PC\\Documents\\NetBeansProjects\\airUcab\\build\\classes\\reporte\\reportHistoria.jasper";
                reporte=(JasperReport) JRLoader.loadObjectFromFile(path);

                JasperPrint jprint=JasperFillManager.fillReport(reporte,null, conexion);
                JasperViewer viewer=new JasperViewer(jprint,false);
                setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                viewer.setVisible(true);
                
            }
            catch(JRException e){
                System.out.println("Error");
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Su Usuario no tiene  el Privilegio  \n De Consultar la Evolución Aeronautica"  , "Acceso No Permitido", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_evolucionAeronauticaActionPerformed

    private void modeloAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloAvionActionPerformed
         nombreEntidad="modelo de aviones";
        if (control.buscarPermiso(instruccion, nombreEntidad,nombreUsuario)==1){
        try{
                Connection conexion = control.conexion();
                
                JasperReport reporte;
                String path="C:\\Users\\GREGORIO-PC\\Documents\\NetBeansProjects\\airUcab\\build\\classes\\reporte\\ReporteModelo.jasper";
                reporte=(JasperReport) JRLoader.loadObjectFromFile(path);

                JasperPrint jprint=JasperFillManager.fillReport(reporte,null, conexion);
                JasperViewer viewer=new JasperViewer(jprint,false);
                setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                viewer.setVisible(true);
                
            }
            catch(JRException e){
                System.out.println("Error");
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Su Usuario no tiene  el Privilegio  \n De Consultar los Modelo de Aviones"  , "Acceso No Permitido", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_modeloAvionActionPerformed

    private void modeloMasVendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloMasVendidoActionPerformed
         nombreEntidad="modelo mas vendido";
        if (control.buscarPermiso(instruccion, nombreEntidad,nombreUsuario)==1){
         try{
                Connection conexion = control.conexion();
                
                JasperReport reporte;
                String path="C:\\Users\\GREGORIO-PC\\Documents\\NetBeansProjects\\airUcab\\build\\classes\\reporte\\ModeloMasVendido.jasper";
                reporte=(JasperReport) JRLoader.loadObjectFromFile(path);

                JasperPrint jprint=JasperFillManager.fillReport(reporte,null, conexion);
                JasperViewer viewer=new JasperViewer(jprint,false);
                setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                viewer.setVisible(true);
                
            }
            catch(JRException e){
                System.out.println("Error");
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Su Usuario no tiene  el Privilegio  \n De Consultar los Modelos mas vendidos"  , "Acceso No Permitido", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_modeloMasVendidoActionPerformed

    private void equipoMasEficienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipoMasEficienteActionPerformed
         nombreEntidad="equipo mas eficiente";
        if (control.buscarPermiso(instruccion, nombreEntidad,nombreUsuario)==1){
        Equipo ventana = new Equipo(nombreUsuario);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
        }
        else
            JOptionPane.showMessageDialog(null, "Su Usuario no tiene  el Privilegio  \n De Consultar el El Equipo Mas Eficiente"  , "Acceso No Permitido", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_equipoMasEficienteActionPerformed

    private void inventarioMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioMensualActionPerformed
        nombreEntidad="inventario";
        if (control.buscarPermiso(instruccion, nombreEntidad,nombreUsuario)==1){
          InventarioMensual ventana = new InventarioMensual(nombreUsuario);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
        }
        else
            JOptionPane.showMessageDialog(null, "Su Usuario no tiene  el Privilegio  \n De Consultar el Inventario"  , "Acceso No Permitido", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_inventarioMensualActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        nombreEntidad="producto inventario";
        if (control.buscarPermiso(instruccion, nombreEntidad,nombreUsuario)==1){
        try{
                Connection conexion = control.conexion();
                
                JasperReport reporte;
                String path="C:\\Users\\GREGORIO-PC\\Documents\\NetBeansProjects\\airUcab\\build\\classes\\reporte\\ProductoMasPedidoInventario.jasper";
                reporte=(JasperReport) JRLoader.loadObjectFromFile(path);

                JasperPrint jprint=JasperFillManager.fillReport(reporte,null, conexion);
                JasperViewer viewer=new JasperViewer(jprint,false);
                setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                viewer.setVisible(true);
                
            }
            catch(JRException e){
                System.out.println("Error");
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Su Usuario no tiene  el Privilegio  \n De Consultar el El Producto mas Pedido al Inventario"  , "Acceso No Permitido", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void tipoAlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoAlaActionPerformed
         nombreEntidad="tipo de ala mas usado";
        if (control.buscarPermiso(instruccion, nombreEntidad,nombreUsuario)==1){
          try{
                Connection conexion = control.conexion();
                
                JasperReport reporte;
                String path="C:\\Users\\GREGORIO-PC\\Documents\\NetBeansProjects\\airUcab\\build\\classes\\reporte\\TipoDeAlaMasUsado.jasper";
                reporte=(JasperReport) JRLoader.loadObjectFromFile(path);

                JasperPrint jprint=JasperFillManager.fillReport(reporte,null, conexion);
                JasperViewer viewer=new JasperViewer(jprint,false);
                setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                viewer.setVisible(true);
                
            }
            catch(JRException e){
                System.out.println("Error");
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Su Usuario no tiene  el Privilegio  \n De Consultar el El Tipo de Ala Mas Utilizado"  , "Acceso No Permitido", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_tipoAlaActionPerformed

    private void avionRentanbleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avionRentanbleActionPerformed
         nombreEntidad="avion mas rentable";
        if (control.buscarPermiso(instruccion, nombreEntidad,nombreUsuario)==1){
        try{
                Connection conexion = control.conexion();
                
                JasperReport reporte;
                String path="C:\\Users\\GREGORIO-PC\\Documents\\NetBeansProjects\\airUcab\\build\\classes\\reporte\\AvionMasRentanble.jasper";
                reporte=(JasperReport) JRLoader.loadObjectFromFile(path);

                JasperPrint jprint=JasperFillManager.fillReport(reporte,null, conexion);
                JasperViewer viewer=new JasperViewer(jprint,false);
                setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                viewer.setVisible(true);
                
            }
            catch(JRException e){
                System.out.println("Error");
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Su Usuario no tiene  el Privilegio  \n De Consultar el El Avión mas Rentable"  , "Acceso No Permitido", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_avionRentanbleActionPerformed

    private void espicificacionModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espicificacionModeloActionPerformed
        nombreEntidad="espicificaciones del modelo";
        if (control.buscarPermiso(instruccion, nombreEntidad,nombreUsuario)==1){
        try {
            Connection conexion = control.conexion();
            JasperReport reporte;
            String path = "C:\\Users\\GREGORIO-PC\\Documents\\NetBeansProjects\\airUcab\\build\\classes\\reporte\\Espicificaciones.jasper";
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path); //Cargo el reporte al objeto
            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, conexion); //Llenado del Reporte con Tres parametros ubicacion,parametros,conexion a la base de datos
            JasperViewer viewer = new JasperViewer(jprint,false); //Creamos la vista del Reporte
             viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE); // Le agregamos que se cierre solo el reporte cuando lo cierre el usuario
            viewer.setVisible(true); //Inicializamos la vista del Reporte
} catch (JRException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else
            JOptionPane.showMessageDialog(null, "Su Usuario no tiene  el Privilegio  \n De Consultar las Espicificaciones de los Modelos"  , "Acceso No Permitido", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_espicificacionModeloActionPerformed

    private void productoPruebaCalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoPruebaCalidadActionPerformed
         nombreEntidad="producto prueba";
        if (control.buscarPermiso(instruccion, nombreEntidad,nombreUsuario)==1){
        try{
                Connection conexion = control.conexion();
                
                JasperReport reporte;
                String path="C:\\Users\\GREGORIO-PC\\Documents\\NetBeansProjects\\airUcab\\build\\classes\\reporte\\ProductoNoCumplieronPrubaCalidad.jasper";
                reporte=(JasperReport) JRLoader.loadObjectFromFile(path);

                JasperPrint jprint=JasperFillManager.fillReport(reporte,null, conexion);
                JasperViewer viewer=new JasperViewer(jprint,false);
                setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                viewer.setVisible(true);
                
            }
            catch(JRException e){
                System.out.println("Error");
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Su Usuario no tiene  el Privilegio  \n De Consultar la Cantidad de Productos que no cumplieron Las Pruebas De Calidad"  , "Acceso No Permitido", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_productoPruebaCalidadActionPerformed

    private void trasladoSedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trasladoSedesActionPerformed
        nombreEntidad="traslado sedes";
        if (control.buscarPermiso(instruccion, nombreEntidad,nombreUsuario)==1){
           try{
                Connection conexion = control.conexion();
                
                JasperReport reporte;
                String path="C:\\Users\\GREGORIO-PC\\Documents\\NetBeansProjects\\airUcab\\build\\classes\\reporte\\PromedioTraslados.jasper";
                reporte=(JasperReport) JRLoader.loadObjectFromFile(path);

                JasperPrint jprint=JasperFillManager.fillReport(reporte,null, conexion);
                JasperViewer viewer=new JasperViewer(jprint,false);
                setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                viewer.setVisible(true);
                
            }
            catch(JRException e){
                System.out.println("Error");
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Su Usuario no tiene  el Privilegio  \n De Consultar el Promedio de Traslados Entre Sedes"  , "Acceso No Permitido", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_trasladoSedesActionPerformed

    private void ListarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarProveedorActionPerformed
         nombreEntidad="listar proveedor";
        if (control.buscarPermiso(instruccion, nombreEntidad,nombreUsuario)==1){
            try{
                Connection conexion = control.conexion();
                
                JasperReport reporte;
                String path="C:\\Users\\GREGORIO-PC\\Documents\\NetBeansProjects\\airUcab\\build\\classes\\reporte\\Proveedor.jasper";
                reporte=(JasperReport) JRLoader.loadObjectFromFile(path);

                JasperPrint jprint=JasperFillManager.fillReport(reporte,null, conexion);
                JasperViewer viewer=new JasperViewer(jprint,false);
                setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                viewer.setVisible(true);
                
            }
            catch(JRException e){
                System.out.println("Error");
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Su Usuario no tiene  el Privilegio  \n De Consultar la Lista De Proveedores"  , "Acceso No Permitido", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_ListarProveedorActionPerformed

    private void plantaEficienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantaEficienteActionPerformed
         nombreEntidad="planta mas eficiente";
        if (control.buscarPermiso(instruccion, nombreEntidad,nombreUsuario)==1){
            Planta ventana = new Planta(nombreUsuario);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
        }
        else
            JOptionPane.showMessageDialog(null, "Su Usuario no tiene  el Privilegio  \n De Consultar la planta mas eficiente"  , "Acceso No Permitido", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_plantaEficienteActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        Home ventana = new Home(nombreUsuario);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_atrasActionPerformed

    private void descripcionPiezasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcionPiezasActionPerformed
       nombreEntidad="descripcion pieza";
        if (control.buscarPermiso(instruccion, nombreEntidad,nombreUsuario)==1){
           try{
                Connection conexion = control.conexion();
                
                JasperReport reporte;
                String path="C:\\Users\\GREGORIO-PC\\Documents\\NetBeansProjects\\airUcab\\build\\classes\\reporte\\reportDescripcion.jasper";
                reporte=(JasperReport) JRLoader.loadObjectFromFile(path);

                JasperPrint jprint=JasperFillManager.fillReport(reporte,null, conexion);
                JasperViewer viewer=new JasperViewer(jprint,false);
                setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                viewer.setVisible(true);
                
            }
            catch(JRException e){
                System.out.println("Error");
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Su Usuario no tiene  el Privilegio  \n De Consultar la Descripción de las Piezas"  , "Acceso No Permitido", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_descripcionPiezasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ListarProveedor;
    private javax.swing.JButton atras;
    private javax.swing.JButton avionRentanble;
    private javax.swing.JButton descripcionPiezas;
    private javax.swing.JButton equipoMasEficiente;
    private javax.swing.JButton espicificacionModelo;
    private javax.swing.JButton evolucionAeronautica;
    private javax.swing.JButton inventarioMensual;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton los10MejoresClientes;
    private javax.swing.JButton mediaAviones;
    private javax.swing.JButton modeloAvion;
    private javax.swing.JButton modeloMasVendido;
    private javax.swing.JButton plantaEficiente;
    private javax.swing.JButton produccionAnual;
    private javax.swing.JButton productoPruebaCalidad;
    private javax.swing.JButton promedioDeProduccionMensual;
    private javax.swing.JButton tipoAla;
    private javax.swing.JButton trasladoSedes;
    // End of variables declaration//GEN-END:variables
}
